// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

export type BusinessObjectChoiceFieldConfigurationDto = {
    selectionMode?: BusinessObjectChoiceSelectionMode;
    options?: Array<BusinessObjectChoiceOptionDto>;
};

export type BusinessObjectChoiceFieldConfigurationInput = {
    selectionMode?: BusinessObjectChoiceSelectionMode;
    options?: Array<BusinessObjectChoiceOptionInput>;
};

export type BusinessObjectChoiceOptionDto = {
    id?: string;
    optionKey?: string;
    label?: string;
    order?: number;
};

export type BusinessObjectChoiceOptionInput = {
    optionKey?: string;
    label?: string;
    id?: string | null;
};

export type BusinessObjectChoiceSelectionMode = 'Single' | 'Multiple';

export type BusinessObjectDefinitionDetailDto = {
    id?: string;
    workspaceId?: string;
    name?: string;
    objectKey?: string;
    status?: BusinessObjectDefinitionStatus;
    revision?: number;
    latestPublishedVersionNumber?: number | null;
    createdAt?: string;
    updatedAt?: string;
    fields?: Array<BusinessObjectFieldDefinitionDto>;
    latestPublishedVersion?: BusinessObjectDefinitionVersionDto;
};

export type BusinessObjectDefinitionListItemDto = {
    id?: string;
    name?: string;
    objectKey?: string;
    status?: BusinessObjectDefinitionStatus;
    revision?: number;
    latestPublishedVersionNumber?: number | null;
    updatedAt?: string;
};

export type BusinessObjectDefinitionListItemDtoPagedResult = {
    items: Array<BusinessObjectDefinitionListItemDto>;
    totalCount: number;
    page: number;
    pageSize: number;
};

export type BusinessObjectDefinitionStatus = 'Unpublished' | 'Published';

export type BusinessObjectDefinitionVersionChoiceFieldConfigurationDto = {
    selectionMode?: BusinessObjectChoiceSelectionMode;
    options?: Array<BusinessObjectDefinitionVersionChoiceOptionDto>;
};

export type BusinessObjectDefinitionVersionChoiceOptionDto = {
    id?: string;
    sourceChoiceOptionId?: string;
    optionKey?: string;
    label?: string;
    order?: number;
};

export type BusinessObjectDefinitionVersionDto = {
    id?: string;
    sourceDefinitionId?: string;
    versionNumber?: number;
    publishedByUserId?: string;
    publishedAt?: string;
    fields?: Array<BusinessObjectDefinitionVersionFieldDto>;
};

export type BusinessObjectDefinitionVersionFieldDto = {
    id?: string;
    sourceFieldDefinitionId?: string;
    fieldKey?: string;
    label?: string;
    order?: number;
    fieldType?: BusinessObjectFieldType;
    choiceConfiguration?: BusinessObjectDefinitionVersionChoiceFieldConfigurationDto;
    rules?: Array<BusinessObjectDefinitionVersionFieldRuleDto>;
};

export type BusinessObjectDefinitionVersionFieldRuleDto = {
    id?: string;
    sourceFieldRuleId?: string;
    bindingId?: string;
    bindingRevision?: number;
    order?: number;
};

export type BusinessObjectFieldDefinitionDto = {
    id?: string;
    fieldKey?: string;
    label?: string;
    order?: number;
    fieldType?: BusinessObjectFieldType;
    choiceConfiguration?: BusinessObjectChoiceFieldConfigurationDto;
    rules?: Array<BusinessObjectFieldRuleDto>;
};

export type BusinessObjectFieldDefinitionInput = {
    fieldKey?: string;
    label?: string;
    fieldType?: BusinessObjectFieldType;
    rules?: Array<BusinessObjectFieldRuleInput> | null;
    choiceConfiguration?: BusinessObjectChoiceFieldConfigurationInput;
    id?: string | null;
};

export type BusinessObjectFieldRuleDto = {
    id?: string;
    bindingId?: string;
    bindingRevision?: number;
    order?: number;
};

export type BusinessObjectFieldRuleInput = {
    bindingId?: string;
    id?: string | null;
};

export type BusinessObjectFieldType = 'Text' | 'Integer' | 'Decimal' | 'Date' | 'DateTime' | 'Boolean' | 'Choice';

export type BusinessObjectRecordDetailDto = {
    id: string;
    workspaceId: string;
    objectKey: string;
    definitionVersion: number;
    definitionVersionId: string;
    status: BusinessObjectRecordStatus;
    revision: number;
    values: {
        [key: string]: Array<string>;
    };
    fields: Array<BusinessObjectRecordFieldContractDto>;
    ruleEvaluations: Array<BusinessObjectRecordRuleEvaluationDto>;
    createdByUserId: string;
    createdAt: string;
    updatedByUserId: string;
    updatedAt: string;
    submittedByUserId?: string | null;
    submittedAt?: string | null;
};

export type BusinessObjectRecordFieldContractDto = {
    fieldKey: string;
    label: string;
    order: number;
    fieldType: BusinessObjectFieldType;
    choiceConfiguration?: BusinessObjectDefinitionVersionChoiceFieldConfigurationDto;
    rules: Array<BusinessObjectDefinitionVersionFieldRuleDto>;
};

export type BusinessObjectRecordListItemDto = {
    id: string;
    objectKey: string;
    definitionVersion: number;
    status: BusinessObjectRecordStatus;
    revision: number;
    updatedAt: string;
    submittedAt?: string | null;
};

export type BusinessObjectRecordListItemDtoPagedResult = {
    items: Array<BusinessObjectRecordListItemDto>;
    totalCount: number;
    page: number;
    pageSize: number;
};

export type BusinessObjectRecordRuleDiagnosticDto = {
    nodeId: string;
    isMatch: boolean;
};

export type BusinessObjectRecordRuleEvaluationDto = {
    fieldKey: string;
    bindingId: string;
    bindingRevision: number;
    definitionKey: string;
    definitionVersion: number;
    isMatch: boolean;
    diagnostics: Array<BusinessObjectRecordRuleDiagnosticDto>;
};

export type BusinessObjectRecordStatus = 'Draft' | 'Submitted';

export type BusinessObjectRecordSubmitResultDto = {
    isSubmitted: boolean;
    record: BusinessObjectRecordDetailDto;
    ruleEvaluations: Array<BusinessObjectRecordRuleEvaluationDto>;
};

export type CreateBusinessObjectDefinitionRequest = {
    name?: string;
};

export type CreateBusinessObjectRecordRequest = {
    idempotencyKey: string;
    values?: {
        [key: string]: Array<string>;
    } | null;
};

export type CreateRuleBindingRequest = {
    definitionKey?: string;
    definitionVersion?: number;
    targetType?: string;
    targetId?: string;
    useCaseOrTrigger?: string;
    inputMappings?: {
        [key: string]: RuleInputMappingDto;
    };
    priority?: number;
    enabled?: boolean;
    failureBehavior?: RuleBindingFailureBehavior;
};

export type CreateRuleDefinitionRequest = {
    name?: string;
    description?: string;
};

export type CurrentUserProfileDto = {
    id?: string;
    email?: string;
    fullName?: string;
    isActive?: boolean;
    language?: string | null;
    theme?: string | null;
    workspaceId?: string | null;
    workspaces?: Array<UserWorkspaceDto>;
};

export type HttpValidationProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    errors?: {
        [key: string]: Array<string>;
    };
    /**
     * Stable machine-readable problem code for client behavior and localization.
     */
    code?: string | null;
    /**
     * Optional field-level machine-readable validation codes keyed by JSON field name.
     */
    errorCodes?: {
        [key: string]: Array<string>;
    } | null;
    [key: string]: unknown;
};

export type LanguagePreferenceDto = {
    language?: string;
};

export type LegalVersionsDto = {
    termsVersion?: string;
    privacyVersion?: string;
};

export type MessageResponse = {
    message?: string;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    /**
     * Stable machine-readable problem code for client behavior and localization.
     */
    code?: string | null;
    /**
     * Optional field-level machine-readable validation codes keyed by JSON field name.
     */
    errorCodes?: {
        [key: string]: Array<string>;
    } | null;
    [key: string]: unknown;
};

export type ProjectRuleConditionRequest = {
    expressionLanguageVersion?: number;
    inputs?: Array<RuleDraftInputDefinitionDto>;
    condition?: RuleConditionNodeDto;
    language?: string;
};

export type PublishBusinessObjectDefinitionRequest = {
    expectedRevision?: number;
};

export type RegisterUserRequest = {
    fullName?: string;
    email?: string;
    password?: string;
    passwordConfirmation?: string;
    acceptedTermsVersion?: string;
    acceptedPrivacyVersion?: string;
    preferredLanguage?: string | null;
};

export type ResendVerificationRequest = {
    email?: string;
};

export type RuleBindingDto = {
    id?: string;
    workspaceId?: string;
    definitionKey?: string;
    definitionVersion?: number;
    targetType?: string;
    targetId?: string;
    useCaseOrTrigger?: string;
    inputMappings?: {
        [key: string]: RuleInputMappingDto;
    };
    priority?: number;
    enabled?: boolean;
    failureBehavior?: RuleBindingFailureBehavior;
    revision?: number;
    createdAt?: string;
    updatedAt?: string;
};

export type RuleBindingFailureBehavior = 'FailClosed' | 'FailOpen';

export type RuleBindingUsageDto = {
    bindingId?: string;
    definitionKey?: string;
    definitionVersion?: number;
    targetType?: string;
    targetId?: string;
    useCaseOrTrigger?: string;
    priority?: number;
    enabled?: boolean;
    failureBehavior?: RuleBindingFailureBehavior;
};

export type RuleConditionNodeDto = {
    nodeId?: string;
    logicalOperator?: RuleLogicalOperator;
    predicateOperator?: RulePredicateOperator;
    left?: RuleOperandDto;
    right?: RuleOperandDto;
    children?: Array<RuleConditionNodeDto>;
};

export type RuleConditionProjectionDto = {
    condition?: RuleConditionNodeDto;
    display?: RuleExpressionDisplayNodeDto;
};

export type RuleDefinitionDetailDto = {
    definitionKey?: string;
    name?: string;
    description?: string;
    origin?: RuleOrigin;
    status?: RuleLifecycleStatus;
    expressionLanguageVersion?: number;
    revision?: number | null;
    latestPublishedVersion?: number | null;
    inputs?: Array<RuleInputDefinitionDto>;
    output?: RuleOutputContractDto;
    condition?: RuleConditionNodeDto;
    versions?: Array<RuleDefinitionVersionDto>;
    createdAt?: string | null;
    updatedAt?: string | null;
    archivedAt?: string | null;
    documentation?: RuleReferenceDocumentationDto;
};

export type RuleDefinitionSummaryDto = {
    definitionKey?: string;
    name?: string;
    description?: string;
    origin?: RuleOrigin;
    status?: RuleLifecycleStatus;
    expressionLanguageVersion?: number;
    revision?: number | null;
    latestPublishedVersion?: number | null;
    inputs?: Array<RuleInputDefinitionDto>;
    output?: RuleOutputContractDto;
    updatedAt?: string | null;
    documentation?: RuleReferenceDocumentationDto;
};

export type RuleDefinitionSummaryDtoPagedResult = {
    items: Array<RuleDefinitionSummaryDto>;
    totalCount: number;
    page: number;
    pageSize: number;
};

export type RuleDefinitionVersionDto = {
    version?: number;
    name?: string;
    description?: string;
    expressionLanguageVersion?: number;
    inputs?: Array<RuleInputDefinitionDto>;
    output?: RuleOutputContractDto;
    condition?: RuleConditionNodeDto;
    publishedByUserId?: string;
    publishedAt?: string;
};

export type RuleDraftInputDefinitionDto = {
    label?: string;
    types?: Array<RuleValueType>;
    isRequired?: boolean;
    allowMultiple?: boolean;
    allowedValues?: Array<string>;
};

export type RuleExpressionCardinality = 'Scalar' | 'Multiple' | 'Any';

export type RuleExpressionCardinalityDefinitionDto = {
    cardinality?: RuleExpressionCardinality;
    documentation?: RuleReferenceDocumentationDto;
};

export type RuleExpressionDisplayNodeDto = {
    nodeId?: string;
    tokens?: Array<RuleExpressionDisplayTokenDto>;
    children?: Array<RuleExpressionDisplayNodeDto>;
};

export type RuleExpressionDisplayTokenDto = {
    text?: string;
    referenceKind?: RuleExpressionReferenceKind;
    referenceKey?: string | null;
    isCode?: boolean;
};

export type RuleExpressionFunction = 'IsBlank' | 'Length' | 'Precision' | 'Scale' | 'Count' | 'MatchesPattern' | 'HasFormat' | 'ToDecimal';

export type RuleExpressionFunctionDefinitionDto = {
    function?: RuleExpressionFunction;
    parameters?: Array<RuleExpressionFunctionParameterDto>;
    returnType?: RuleValueType;
    returnCardinality?: RuleExpressionCardinality;
    documentation?: RuleReferenceDocumentationDto;
};

export type RuleExpressionFunctionParameterDto = {
    acceptedTypes?: Array<RuleValueType>;
    cardinality?: RuleExpressionCardinality;
};

export type RuleExpressionGuideDto = {
    expressionLanguageVersion?: number;
    totalResults?: number;
    sections?: Array<RuleExpressionGuideSectionDto>;
};

export type RuleExpressionGuideItemDto = {
    referenceKind?: RuleExpressionReferenceKind;
    referenceKey?: string;
    displayName?: SearchTextDto;
    summary?: SearchTextDto;
    usage?: SearchTextDto;
    examples?: Array<SearchTextDto>;
    detail?: SearchTextDto;
};

export type RuleExpressionGuideSectionDto = {
    key?: string;
    title?: string;
    description?: string;
    items?: Array<RuleExpressionGuideItemDto>;
};

export type RuleExpressionLanguageDto = {
    version?: number;
    operators?: Array<RulePredicateOperatorDefinitionDto>;
    functions?: Array<RuleExpressionFunctionDefinitionDto>;
    logicalOperators?: Array<RuleLogicalOperatorDefinitionDto>;
    operandKinds?: Array<RuleOperandKindDefinitionDto>;
    valueTypes?: Array<RuleValueTypeDefinitionDto>;
    cardinalities?: Array<RuleExpressionCardinalityDefinitionDto>;
    limitDefinitions?: Array<RuleExpressionLimitDefinitionDto>;
    limits?: RuleExpressionLimitsDto;
};

export type RuleExpressionLimitDefinitionDto = {
    key?: string;
    value?: number;
    documentation?: RuleReferenceDocumentationDto;
};

export type RuleExpressionLimitsDto = {
    maxDepth?: number;
    maxNodes?: number;
    maxFunctionCalls?: number;
    maxInputs?: number;
    maxExecutionSteps?: number;
};

export type RuleExpressionReferenceKind = 'LogicalOperator' | 'PredicateOperator' | 'Function' | 'Input' | 'Literal' | 'ValueType' | 'OperandKind' | 'Limit';

export type RuleExpressionValueShapeDto = {
    type?: RuleValueType;
    cardinality?: RuleExpressionCardinality;
};

export type RuleInputDefinitionDto = {
    key?: string;
    label?: string;
    types?: Array<RuleValueType>;
    isRequired?: boolean;
    allowMultiple?: boolean;
    allowedValues?: Array<string>;
};

export type RuleInputMappingDto = {
    kind?: RuleInputMappingKind;
    contextKey?: string | null;
    literalValues?: Array<string>;
};

export type RuleInputMappingKind = 'Context' | 'Literal';

export type RuleLifecycleStatus = 'Draft' | 'Published' | 'Archived';

export type RuleLogicalOperator = 'All' | 'Any' | 'Not';

export type RuleLogicalOperatorDefinitionDto = {
    operator?: RuleLogicalOperator;
    minimumChildren?: number;
    maximumChildren?: number | null;
    documentation?: RuleReferenceDocumentationDto;
};

export type RuleNodeDiagnosticDto = {
    nodeId?: string;
    isMatch?: boolean;
};

export type RuleOperandDto = {
    kind?: RuleOperandKind;
    reference?: string | null;
    literal?: RuleValueDto;
    function?: RuleExpressionFunction;
    arguments?: Array<RuleOperandDto> | null;
};

export type RuleOperandKind = 'Input' | 'Literal' | 'Function';

export type RuleOperandKindDefinitionDto = {
    kind?: RuleOperandKind;
    documentation?: RuleReferenceDocumentationDto;
};

export type RuleOrigin = 'System' | 'Workspace';

export type RuleOutputContractDto = {
    type?: RuleValueType;
    cardinality?: RuleExpressionCardinality;
};

export type RulePredicateOperator = 'Equal' | 'NotEqual' | 'GreaterThan' | 'GreaterThanOrEqual' | 'LessThan' | 'LessThanOrEqual' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull';

export type RulePredicateOperatorDefinitionDto = {
    operator?: RulePredicateOperator;
    leftShapes?: Array<RuleExpressionValueShapeDto>;
    rightShapes?: Array<RuleExpressionValueShapeDto>;
    requiresMatchingTypes?: boolean;
    documentation?: RuleReferenceDocumentationDto;
};

export type RuleReferenceContentDto = {
    displayName?: string;
    summary?: string;
    usage?: string;
    examples?: Array<string>;
};

export type RuleReferenceDocumentationDto = {
    locales?: {
        [key: string]: RuleReferenceContentDto;
    };
};

export type RuleRevisionRequest = {
    expectedRevision?: number;
};

export type RuleSimulationResultDto = {
    definitionKey?: string;
    definitionVersion?: number | null;
    isMatch?: boolean;
    diagnostics?: Array<RuleNodeDiagnosticDto>;
    correlationId?: string;
};

export type RuleValueDto = {
    type?: RuleValueType;
    values?: Array<string>;
};

export type RuleValueType = 'Text' | 'Integer' | 'Decimal' | 'Date' | 'DateTime' | 'Boolean';

export type RuleValueTypeDefinitionDto = {
    type?: RuleValueType;
    documentation?: RuleReferenceDocumentationDto;
};

export type SaveBusinessObjectRecordRequest = {
    expectedRevision: number;
    values: {
        [key: string]: Array<string>;
    };
};

export type SaveRuleDefinitionDraftRequest = {
    expectedRevision?: number;
    name?: string;
    description?: string;
    inputs?: Array<RuleDraftInputDefinitionDto>;
    condition?: RuleConditionNodeDto;
};

export type SaveUnpublishedBusinessObjectDefinitionRequest = {
    expectedRevision?: number;
    name?: string;
    fields?: Array<BusinessObjectFieldDefinitionInput>;
};

export type SearchRuleExpressionGuideRequest = {
    expressionLanguageVersion?: number;
    definitionKey?: string | null;
    inputs?: Array<RuleInputDefinitionDto>;
    query?: string | null;
    language?: string;
};

export type SearchTextDto = {
    text?: string;
    segments?: Array<SearchTextSegmentDto>;
};

export type SearchTextSegmentDto = {
    text?: string;
    isMatch?: boolean;
};

export type SignInNextStep = 'Dashboard';

export type SignInSessionEstablishedDto = {
    sessionEstablished?: boolean;
    nextStep?: SignInNextStep;
};

export type SignInUserRequest = {
    email?: string;
    password?: string;
};

export type SimulateRuleRequest = {
    definitionVersion?: number | null;
    inputs?: {
        [key: string]: RuleValueDto;
    };
    correlationId?: string;
};

export type SubmitBusinessObjectRecordRequest = {
    expectedRevision: number;
};

export type ThemePreferenceDto = {
    theme?: string;
};

export type UpdateRuleBindingRequest = {
    expectedRevision?: number;
    definitionKey?: string;
    definitionVersion?: number;
    targetType?: string;
    targetId?: string;
    useCaseOrTrigger?: string;
    inputMappings?: {
        [key: string]: RuleInputMappingDto;
    };
    priority?: number;
    enabled?: boolean;
    failureBehavior?: RuleBindingFailureBehavior;
};

export type UpdateUserLanguagePreferenceRequest = {
    language?: string;
};

export type UpdateUserThemePreferenceRequest = {
    theme?: string;
};

export type UserWorkspaceDto = {
    id?: string;
    name?: string;
    slug?: string;
    type?: string;
    isCurrent?: boolean;
};

export type VerifyEmailNextStep = 'Dashboard';

export type VerifyEmailRequest = {
    token?: string;
};

export type VerifyEmailSessionEstablishedDto = {
    sessionEstablished?: boolean;
    nextStep?: VerifyEmailNextStep;
};

export type ListBusinessObjectRecordsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
        objectKey?: string;
    };
    url: '/api/business-object-records';
};

export type ListBusinessObjectRecordsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
};

export type ListBusinessObjectRecordsError = ListBusinessObjectRecordsErrors[keyof ListBusinessObjectRecordsErrors];

export type ListBusinessObjectRecordsResponses = {
    /**
     * OK
     */
    200: BusinessObjectRecordListItemDtoPagedResult;
};

export type ListBusinessObjectRecordsResponse = ListBusinessObjectRecordsResponses[keyof ListBusinessObjectRecordsResponses];

export type CreateBusinessObjectRecordData = {
    body: CreateBusinessObjectRecordRequest;
    path: {
        objectKey: string;
    };
    query?: never;
    url: '/api/business-object-records/{objectKey}';
};

export type CreateBusinessObjectRecordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Unprocessable Content
     */
    422: ProblemDetails;
};

export type CreateBusinessObjectRecordError = CreateBusinessObjectRecordErrors[keyof CreateBusinessObjectRecordErrors];

export type CreateBusinessObjectRecordResponses = {
    /**
     * Created
     */
    201: BusinessObjectRecordDetailDto;
};

export type CreateBusinessObjectRecordResponse = CreateBusinessObjectRecordResponses[keyof CreateBusinessObjectRecordResponses];

export type GetBusinessObjectRecordData = {
    body?: never;
    path: {
        recordId: string;
    };
    query?: never;
    url: '/api/business-object-records/{recordId}';
};

export type GetBusinessObjectRecordErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetBusinessObjectRecordError = GetBusinessObjectRecordErrors[keyof GetBusinessObjectRecordErrors];

export type GetBusinessObjectRecordResponses = {
    /**
     * OK
     */
    200: BusinessObjectRecordDetailDto;
};

export type GetBusinessObjectRecordResponse = GetBusinessObjectRecordResponses[keyof GetBusinessObjectRecordResponses];

export type SaveBusinessObjectRecordData = {
    body: SaveBusinessObjectRecordRequest;
    path: {
        recordId: string;
    };
    query?: never;
    url: '/api/business-object-records/{recordId}';
};

export type SaveBusinessObjectRecordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Unprocessable Content
     */
    422: ProblemDetails;
};

export type SaveBusinessObjectRecordError = SaveBusinessObjectRecordErrors[keyof SaveBusinessObjectRecordErrors];

export type SaveBusinessObjectRecordResponses = {
    /**
     * OK
     */
    200: BusinessObjectRecordDetailDto;
};

export type SaveBusinessObjectRecordResponse = SaveBusinessObjectRecordResponses[keyof SaveBusinessObjectRecordResponses];

export type SubmitBusinessObjectRecordData = {
    body: SubmitBusinessObjectRecordRequest;
    path: {
        recordId: string;
    };
    query?: never;
    url: '/api/business-object-records/{recordId}/submit';
};

export type SubmitBusinessObjectRecordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Unprocessable Content
     */
    422: ProblemDetails;
};

export type SubmitBusinessObjectRecordError = SubmitBusinessObjectRecordErrors[keyof SubmitBusinessObjectRecordErrors];

export type SubmitBusinessObjectRecordResponses = {
    /**
     * OK
     */
    200: BusinessObjectRecordSubmitResultDto;
};

export type SubmitBusinessObjectRecordResponse = SubmitBusinessObjectRecordResponses[keyof SubmitBusinessObjectRecordResponses];

export type ListBusinessObjectDefinitionsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
        query?: string;
        language?: string;
    };
    url: '/api/business-object-definitions';
};

export type ListBusinessObjectDefinitionsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
};

export type ListBusinessObjectDefinitionsError = ListBusinessObjectDefinitionsErrors[keyof ListBusinessObjectDefinitionsErrors];

export type ListBusinessObjectDefinitionsResponses = {
    /**
     * OK
     */
    200: BusinessObjectDefinitionListItemDtoPagedResult;
};

export type ListBusinessObjectDefinitionsResponse = ListBusinessObjectDefinitionsResponses[keyof ListBusinessObjectDefinitionsResponses];

export type CreateBusinessObjectDefinitionData = {
    body: CreateBusinessObjectDefinitionRequest;
    path?: never;
    query?: never;
    url: '/api/business-object-definitions';
};

export type CreateBusinessObjectDefinitionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type CreateBusinessObjectDefinitionError = CreateBusinessObjectDefinitionErrors[keyof CreateBusinessObjectDefinitionErrors];

export type CreateBusinessObjectDefinitionResponses = {
    /**
     * Created
     */
    201: BusinessObjectDefinitionDetailDto;
};

export type CreateBusinessObjectDefinitionResponse = CreateBusinessObjectDefinitionResponses[keyof CreateBusinessObjectDefinitionResponses];

export type GetBusinessObjectDefinitionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/business-object-definitions/{id}';
};

export type GetBusinessObjectDefinitionErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetBusinessObjectDefinitionError = GetBusinessObjectDefinitionErrors[keyof GetBusinessObjectDefinitionErrors];

export type GetBusinessObjectDefinitionResponses = {
    /**
     * OK
     */
    200: BusinessObjectDefinitionDetailDto;
};

export type GetBusinessObjectDefinitionResponse = GetBusinessObjectDefinitionResponses[keyof GetBusinessObjectDefinitionResponses];

export type SaveUnpublishedBusinessObjectDefinitionData = {
    body: SaveUnpublishedBusinessObjectDefinitionRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/business-object-definitions/{id}/unpublished';
};

export type SaveUnpublishedBusinessObjectDefinitionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type SaveUnpublishedBusinessObjectDefinitionError = SaveUnpublishedBusinessObjectDefinitionErrors[keyof SaveUnpublishedBusinessObjectDefinitionErrors];

export type SaveUnpublishedBusinessObjectDefinitionResponses = {
    /**
     * OK
     */
    200: BusinessObjectDefinitionDetailDto;
};

export type SaveUnpublishedBusinessObjectDefinitionResponse = SaveUnpublishedBusinessObjectDefinitionResponses[keyof SaveUnpublishedBusinessObjectDefinitionResponses];

export type PublishBusinessObjectDefinitionData = {
    body: PublishBusinessObjectDefinitionRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/business-object-definitions/{id}/publish';
};

export type PublishBusinessObjectDefinitionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type PublishBusinessObjectDefinitionError = PublishBusinessObjectDefinitionErrors[keyof PublishBusinessObjectDefinitionErrors];

export type PublishBusinessObjectDefinitionResponses = {
    /**
     * OK
     */
    200: BusinessObjectDefinitionDetailDto;
};

export type PublishBusinessObjectDefinitionResponse = PublishBusinessObjectDefinitionResponses[keyof PublishBusinessObjectDefinitionResponses];

export type GetLegalVersionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/legal/versions';
};

export type GetLegalVersionsResponses = {
    /**
     * OK
     */
    200: LegalVersionsDto;
};

export type GetLegalVersionsResponse = GetLegalVersionsResponses[keyof GetLegalVersionsResponses];

export type SignInUserData = {
    body: SignInUserRequest;
    path?: never;
    query?: never;
    url: '/api/auth/sign-in';
};

export type SignInUserErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unprocessable Content
     */
    422: ProblemDetails;
    /**
     * Too Many Requests
     */
    429: ProblemDetails;
};

export type SignInUserError = SignInUserErrors[keyof SignInUserErrors];

export type SignInUserResponses = {
    /**
     * OK
     */
    200: SignInSessionEstablishedDto;
};

export type SignInUserResponse = SignInUserResponses[keyof SignInUserResponses];

export type VerifyEmailData = {
    body: VerifyEmailRequest;
    path?: never;
    query?: never;
    url: '/api/auth/verify-email';
};

export type VerifyEmailErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type VerifyEmailError = VerifyEmailErrors[keyof VerifyEmailErrors];

export type VerifyEmailResponses = {
    /**
     * OK
     */
    200: VerifyEmailSessionEstablishedDto;
};

export type VerifyEmailResponse = VerifyEmailResponses[keyof VerifyEmailResponses];

export type ResendEmailVerificationData = {
    body: ResendVerificationRequest;
    path?: never;
    query?: never;
    url: '/api/auth/resend-verification';
};

export type ResendEmailVerificationErrors = {
    /**
     * Too Many Requests
     */
    429: ProblemDetails;
};

export type ResendEmailVerificationError = ResendEmailVerificationErrors[keyof ResendEmailVerificationErrors];

export type ResendEmailVerificationResponses = {
    /**
     * No Content
     */
    204: void;
};

export type ResendEmailVerificationResponse = ResendEmailVerificationResponses[keyof ResendEmailVerificationResponses];

export type SignOutUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/sign-out';
};

export type SignOutUserResponses = {
    /**
     * No Content
     */
    204: void;
};

export type SignOutUserResponse = SignOutUserResponses[keyof SignOutUserResponses];

export type RegisterUserData = {
    body: RegisterUserRequest;
    path?: never;
    query?: never;
    url: '/api/users/register';
};

export type RegisterUserErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type RegisterUserError = RegisterUserErrors[keyof RegisterUserErrors];

export type RegisterUserResponses = {
    /**
     * OK
     */
    200: MessageResponse;
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type GetMeErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * OK
     */
    200: CurrentUserProfileDto;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type UpdateLanguagePreferenceData = {
    body: UpdateUserLanguagePreferenceRequest;
    path?: never;
    query?: never;
    url: '/api/users/me/preferences/language';
};

export type UpdateLanguagePreferenceErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateLanguagePreferenceError = UpdateLanguagePreferenceErrors[keyof UpdateLanguagePreferenceErrors];

export type UpdateLanguagePreferenceResponses = {
    /**
     * OK
     */
    200: LanguagePreferenceDto;
};

export type UpdateLanguagePreferenceResponse = UpdateLanguagePreferenceResponses[keyof UpdateLanguagePreferenceResponses];

export type UpdateThemePreferenceData = {
    body: UpdateUserThemePreferenceRequest;
    path?: never;
    query?: never;
    url: '/api/users/me/preferences/theme';
};

export type UpdateThemePreferenceErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateThemePreferenceError = UpdateThemePreferenceErrors[keyof UpdateThemePreferenceErrors];

export type UpdateThemePreferenceResponses = {
    /**
     * OK
     */
    200: ThemePreferenceDto;
};

export type UpdateThemePreferenceResponse = UpdateThemePreferenceResponses[keyof UpdateThemePreferenceResponses];

export type ListRuleBindingUsageData = {
    body?: never;
    path: {
        definitionKey: string;
    };
    query: {
        version: number;
    };
    url: '/api/rules/{definitionKey}/bindings';
};

export type ListRuleBindingUsageErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
};

export type ListRuleBindingUsageError = ListRuleBindingUsageErrors[keyof ListRuleBindingUsageErrors];

export type ListRuleBindingUsageResponses = {
    /**
     * OK
     */
    200: Array<RuleBindingUsageDto>;
};

export type ListRuleBindingUsageResponse = ListRuleBindingUsageResponses[keyof ListRuleBindingUsageResponses];

export type ListRuleDefinitionsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
        origin?: RuleOrigin;
        status?: RuleLifecycleStatus;
        query?: string;
        language?: string;
    };
    url: '/api/rules';
};

export type ListRuleDefinitionsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
};

export type ListRuleDefinitionsError = ListRuleDefinitionsErrors[keyof ListRuleDefinitionsErrors];

export type ListRuleDefinitionsResponses = {
    /**
     * OK
     */
    200: RuleDefinitionSummaryDtoPagedResult;
};

export type ListRuleDefinitionsResponse = ListRuleDefinitionsResponses[keyof ListRuleDefinitionsResponses];

export type CreateRuleDefinitionData = {
    body: CreateRuleDefinitionRequest;
    path?: never;
    query?: never;
    url: '/api/rules';
};

export type CreateRuleDefinitionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type CreateRuleDefinitionError = CreateRuleDefinitionErrors[keyof CreateRuleDefinitionErrors];

export type CreateRuleDefinitionResponses = {
    /**
     * Created
     */
    201: RuleDefinitionDetailDto;
};

export type CreateRuleDefinitionResponse = CreateRuleDefinitionResponses[keyof CreateRuleDefinitionResponses];

export type GetRuleExpressionLanguageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rules/expression-language';
};

export type GetRuleExpressionLanguageErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
};

export type GetRuleExpressionLanguageError = GetRuleExpressionLanguageErrors[keyof GetRuleExpressionLanguageErrors];

export type GetRuleExpressionLanguageResponses = {
    /**
     * OK
     */
    200: RuleExpressionLanguageDto;
};

export type GetRuleExpressionLanguageResponse = GetRuleExpressionLanguageResponses[keyof GetRuleExpressionLanguageResponses];

export type ProjectRuleConditionData = {
    body: ProjectRuleConditionRequest;
    path?: never;
    query?: never;
    url: '/api/rules/condition/project';
};

export type ProjectRuleConditionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
};

export type ProjectRuleConditionError = ProjectRuleConditionErrors[keyof ProjectRuleConditionErrors];

export type ProjectRuleConditionResponses = {
    /**
     * OK
     */
    200: RuleConditionProjectionDto;
};

export type ProjectRuleConditionResponse = ProjectRuleConditionResponses[keyof ProjectRuleConditionResponses];

export type SearchRuleExpressionGuideData = {
    body: SearchRuleExpressionGuideRequest;
    path?: never;
    query?: never;
    url: '/api/rules/expression-language/guide';
};

export type SearchRuleExpressionGuideErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
};

export type SearchRuleExpressionGuideError = SearchRuleExpressionGuideErrors[keyof SearchRuleExpressionGuideErrors];

export type SearchRuleExpressionGuideResponses = {
    /**
     * OK
     */
    200: RuleExpressionGuideDto;
};

export type SearchRuleExpressionGuideResponse = SearchRuleExpressionGuideResponses[keyof SearchRuleExpressionGuideResponses];

export type GetRuleDefinitionData = {
    body?: never;
    path: {
        definitionKey: string;
    };
    query?: never;
    url: '/api/rules/{definitionKey}';
};

export type GetRuleDefinitionErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetRuleDefinitionError = GetRuleDefinitionErrors[keyof GetRuleDefinitionErrors];

export type GetRuleDefinitionResponses = {
    /**
     * OK
     */
    200: RuleDefinitionDetailDto;
};

export type GetRuleDefinitionResponse = GetRuleDefinitionResponses[keyof GetRuleDefinitionResponses];

export type StartRuleDefinitionDraftData = {
    body: RuleRevisionRequest;
    path: {
        definitionKey: string;
    };
    query?: never;
    url: '/api/rules/{definitionKey}/draft';
};

export type StartRuleDefinitionDraftErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type StartRuleDefinitionDraftError = StartRuleDefinitionDraftErrors[keyof StartRuleDefinitionDraftErrors];

export type StartRuleDefinitionDraftResponses = {
    /**
     * OK
     */
    200: RuleDefinitionDetailDto;
};

export type StartRuleDefinitionDraftResponse = StartRuleDefinitionDraftResponses[keyof StartRuleDefinitionDraftResponses];

export type SaveRuleDefinitionDraftData = {
    body: SaveRuleDefinitionDraftRequest;
    path: {
        definitionKey: string;
    };
    query?: never;
    url: '/api/rules/{definitionKey}/draft';
};

export type SaveRuleDefinitionDraftErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type SaveRuleDefinitionDraftError = SaveRuleDefinitionDraftErrors[keyof SaveRuleDefinitionDraftErrors];

export type SaveRuleDefinitionDraftResponses = {
    /**
     * OK
     */
    200: RuleDefinitionDetailDto;
};

export type SaveRuleDefinitionDraftResponse = SaveRuleDefinitionDraftResponses[keyof SaveRuleDefinitionDraftResponses];

export type PublishRuleDefinitionData = {
    body: RuleRevisionRequest;
    path: {
        definitionKey: string;
    };
    query?: never;
    url: '/api/rules/{definitionKey}/publish';
};

export type PublishRuleDefinitionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type PublishRuleDefinitionError = PublishRuleDefinitionErrors[keyof PublishRuleDefinitionErrors];

export type PublishRuleDefinitionResponses = {
    /**
     * OK
     */
    200: RuleDefinitionDetailDto;
};

export type PublishRuleDefinitionResponse = PublishRuleDefinitionResponses[keyof PublishRuleDefinitionResponses];

export type ArchiveRuleDefinitionData = {
    body: RuleRevisionRequest;
    path: {
        definitionKey: string;
    };
    query?: never;
    url: '/api/rules/{definitionKey}/archive';
};

export type ArchiveRuleDefinitionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type ArchiveRuleDefinitionError = ArchiveRuleDefinitionErrors[keyof ArchiveRuleDefinitionErrors];

export type ArchiveRuleDefinitionResponses = {
    /**
     * OK
     */
    200: RuleDefinitionDetailDto;
};

export type ArchiveRuleDefinitionResponse = ArchiveRuleDefinitionResponses[keyof ArchiveRuleDefinitionResponses];

export type SimulateRuleDefinitionData = {
    body: SimulateRuleRequest;
    path: {
        definitionKey: string;
    };
    query?: never;
    url: '/api/rules/{definitionKey}/simulate';
};

export type SimulateRuleDefinitionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type SimulateRuleDefinitionError = SimulateRuleDefinitionErrors[keyof SimulateRuleDefinitionErrors];

export type SimulateRuleDefinitionResponses = {
    /**
     * OK
     */
    200: RuleSimulationResultDto;
};

export type SimulateRuleDefinitionResponse = SimulateRuleDefinitionResponses[keyof SimulateRuleDefinitionResponses];

export type CreateRuleBindingData = {
    body: CreateRuleBindingRequest;
    path?: never;
    query?: never;
    url: '/api/rule-bindings';
};

export type CreateRuleBindingErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type CreateRuleBindingError = CreateRuleBindingErrors[keyof CreateRuleBindingErrors];

export type CreateRuleBindingResponses = {
    /**
     * Created
     */
    201: RuleBindingDto;
};

export type CreateRuleBindingResponse = CreateRuleBindingResponses[keyof CreateRuleBindingResponses];

export type DeleteRuleBindingData = {
    body?: never;
    path: {
        bindingId: string;
    };
    query?: never;
    url: '/api/rule-bindings/{bindingId}';
};

export type DeleteRuleBindingErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteRuleBindingError = DeleteRuleBindingErrors[keyof DeleteRuleBindingErrors];

export type DeleteRuleBindingResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRuleBindingResponse = DeleteRuleBindingResponses[keyof DeleteRuleBindingResponses];

export type GetRuleBindingData = {
    body?: never;
    path: {
        bindingId: string;
    };
    query?: never;
    url: '/api/rule-bindings/{bindingId}';
};

export type GetRuleBindingErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetRuleBindingError = GetRuleBindingErrors[keyof GetRuleBindingErrors];

export type GetRuleBindingResponses = {
    /**
     * OK
     */
    200: RuleBindingDto;
};

export type GetRuleBindingResponse = GetRuleBindingResponses[keyof GetRuleBindingResponses];

export type UpdateRuleBindingData = {
    body: UpdateRuleBindingRequest;
    path: {
        bindingId: string;
    };
    query?: never;
    url: '/api/rule-bindings/{bindingId}';
};

export type UpdateRuleBindingErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type UpdateRuleBindingError = UpdateRuleBindingErrors[keyof UpdateRuleBindingErrors];

export type UpdateRuleBindingResponses = {
    /**
     * OK
     */
    200: RuleBindingDto;
};

export type UpdateRuleBindingResponse = UpdateRuleBindingResponses[keyof UpdateRuleBindingResponses];
