// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

export type ActivateRuleDefinitionVersionRequest = {
    version?: number;
    expectedRevision?: number;
};

export type AssignProductRoleBody = {
    target?: SubjectReferenceDto;
    policyVersionId?: string;
    roleKey?: string;
    expectedRevision?: number | null;
};

export type AssignableSubjectDto = {
    subject?: SubjectReferenceDto;
    displayName?: string;
    secondaryLabel?: string | null;
};

export type AxisBrowserSessionDto = {
    authenticated?: boolean;
    csrfToken?: string;
    user?: AxisBrowserSessionUserDto;
};

export type AxisBrowserSessionUserDto = {
    userId?: string;
    workspaceId?: string | null;
    email?: string;
    name?: string;
};

export type BusinessObjectChoiceFieldConfigurationDto = {
    selectionMode?: BusinessObjectChoiceSelectionMode;
    options?: Array<BusinessObjectChoiceOptionDto>;
};

export type BusinessObjectChoiceFieldConfigurationInput = {
    selectionMode?: BusinessObjectChoiceSelectionMode;
    options?: Array<BusinessObjectChoiceOptionInput>;
};

export type BusinessObjectChoiceOptionDto = {
    id?: string;
    optionKey?: string;
    label?: string;
    order?: number;
};

export type BusinessObjectChoiceOptionInput = {
    optionKey?: string;
    label?: string;
    id?: string | null;
};

export type BusinessObjectChoiceSelectionMode = 'Single' | 'Multiple';

export type BusinessObjectDefinitionActionsDto = {
    canSave?: boolean;
    canPublish?: boolean;
};

export type BusinessObjectDefinitionCollectionActionsDto = {
    canStartCreate?: boolean;
};

export type BusinessObjectDefinitionDetailDto = {
    id?: string;
    workspaceId?: string;
    name?: string;
    objectKey?: string;
    status?: BusinessObjectDefinitionStatus;
    revision?: number;
    latestPublishedVersionNumber?: number | null;
    createdAt?: string;
    updatedAt?: string;
    fields?: Array<BusinessObjectFieldDefinitionDto>;
    latestPublishedVersion?: BusinessObjectDefinitionVersionDto;
    actions?: BusinessObjectDefinitionActionsDto;
};

export type BusinessObjectDefinitionListItemDto = {
    id?: string;
    name?: string;
    objectKey?: string;
    status?: BusinessObjectDefinitionStatus;
    revision?: number;
    latestPublishedVersionNumber?: number | null;
    updatedAt?: string;
};

export type BusinessObjectDefinitionListItemDtoPagedResult = {
    items: Array<BusinessObjectDefinitionListItemDto>;
    totalCount: number;
    page: number;
    pageSize: number;
};

export type BusinessObjectDefinitionStatus = 'Unpublished' | 'Published';

export type BusinessObjectDefinitionVersionChoiceFieldConfigurationDto = {
    selectionMode?: BusinessObjectChoiceSelectionMode;
    options?: Array<BusinessObjectDefinitionVersionChoiceOptionDto>;
};

export type BusinessObjectDefinitionVersionChoiceOptionDto = {
    id?: string;
    sourceChoiceOptionId?: string;
    optionKey?: string;
    label?: string;
    order?: number;
};

export type BusinessObjectDefinitionVersionDto = {
    id?: string;
    sourceDefinitionId?: string;
    versionNumber?: number;
    publishedBySubject?: SubjectReferenceDto;
    publishedAt?: string;
    fields?: Array<BusinessObjectDefinitionVersionFieldDto>;
};

export type BusinessObjectDefinitionVersionFieldDto = {
    id?: string;
    sourceFieldDefinitionId?: string;
    fieldKey?: string;
    label?: string;
    order?: number;
    fieldType?: BusinessObjectFieldType;
    choiceConfiguration?: BusinessObjectDefinitionVersionChoiceFieldConfigurationDto;
    rules?: Array<BusinessObjectDefinitionVersionFieldRuleDto>;
};

export type BusinessObjectDefinitionVersionFieldRuleDto = {
    id?: string;
    sourceFieldRuleId?: string;
    bindingId?: string;
    bindingRevision?: number;
    order?: number;
};

export type BusinessObjectFieldDefinitionDto = {
    id?: string;
    fieldKey?: string;
    label?: string;
    order?: number;
    fieldType?: BusinessObjectFieldType;
    choiceConfiguration?: BusinessObjectChoiceFieldConfigurationDto;
    rules?: Array<BusinessObjectFieldRuleDto>;
};

export type BusinessObjectFieldDefinitionInput = {
    fieldKey?: string;
    label?: string;
    fieldType?: BusinessObjectFieldType;
    rules?: Array<BusinessObjectFieldRuleInput> | null;
    choiceConfiguration?: BusinessObjectChoiceFieldConfigurationInput;
    id?: string | null;
};

export type BusinessObjectFieldRuleDto = {
    id?: string;
    bindingId?: string;
    bindingRevision?: number;
    order?: number;
};

export type BusinessObjectFieldRuleInput = {
    bindingId?: string;
    id?: string | null;
};

export type BusinessObjectFieldType = 'Text' | 'Integer' | 'Decimal' | 'Date' | 'DateTime' | 'Boolean' | 'Choice';

export type BusinessObjectRecordDetailDto = {
    id: string;
    workspaceId: string;
    objectKey: string;
    definitionVersion: number;
    definitionVersionId: string;
    status: BusinessObjectRecordStatus;
    revision: number;
    values: {
        [key: string]: Array<string>;
    };
    fields: Array<BusinessObjectRecordFieldContractDto>;
    ruleEvaluations: Array<BusinessObjectRecordRuleEvaluationDto>;
    createdBySubject: SubjectReferenceDto;
    createdAt: string;
    updatedBySubject: SubjectReferenceDto;
    updatedAt: string;
    submittedBySubject?: SubjectReferenceDto;
    submittedAt?: string | null;
};

export type BusinessObjectRecordFieldContractDto = {
    fieldKey: string;
    label: string;
    order: number;
    fieldType: BusinessObjectFieldType;
    choiceConfiguration?: BusinessObjectDefinitionVersionChoiceFieldConfigurationDto;
    rules: Array<BusinessObjectDefinitionVersionFieldRuleDto>;
};

export type BusinessObjectRecordListItemDto = {
    id: string;
    objectKey: string;
    definitionVersion: number;
    status: BusinessObjectRecordStatus;
    revision: number;
    updatedAt: string;
    submittedAt?: string | null;
};

export type BusinessObjectRecordListItemDtoPagedResult = {
    items: Array<BusinessObjectRecordListItemDto>;
    totalCount: number;
    page: number;
    pageSize: number;
};

export type BusinessObjectRecordRuleDiagnosticDto = {
    nodeId: string;
    isMatch: boolean;
};

export type BusinessObjectRecordRuleEvaluationDto = {
    fieldKey: string;
    bindingId: string;
    bindingRevision: number;
    definitionKey: string;
    definitionVersion: number;
    isMatch: boolean;
    diagnostics: Array<BusinessObjectRecordRuleDiagnosticDto>;
};

export type BusinessObjectRecordStatus = 'Draft' | 'Submitted';

export type BusinessObjectRecordSubmitResultDto = {
    isSubmitted: boolean;
    record: BusinessObjectRecordDetailDto;
    ruleEvaluations: Array<BusinessObjectRecordRuleEvaluationDto>;
};

export type ChangeWorkspaceInvitationRequest = {
    expectedRevision?: number;
};

export type ChangeWorkspaceProductBuilderRequest = {
    expectedRevision?: number;
};

export type CompleteRuleAuthoringRequest = {
    text?: string | null;
    cursor?: number;
    inputs?: Array<RuleInputDefinitionDto>;
    expressionLanguageVersion?: number;
};

export type CreateBusinessObjectDefinitionRequest = {
    name?: string;
};

export type CreateBusinessObjectRecordRequest = {
    idempotencyKey: string;
    values?: {
        [key: string]: Array<string>;
    } | null;
};

export type CreateOrganizationWorkspaceDto = {
    organizationId?: string;
    organizationName?: string;
    workspaceId?: string;
    workspaceName?: string;
    workspaceSlug?: string;
};

export type CreateOrganizationWorkspaceRequest = {
    name?: string;
};

export type CreateRequest = {
    clientId?: string;
};

export type CreateRuleBindingRequest = {
    definitionKey?: string;
    definitionVersion?: number;
    targetType?: string;
    targetId?: string;
    useCaseOrTrigger?: string;
    inputMappings?: {
        [key: string]: RuleInputMappingDto;
    };
    priority?: number;
    enabled?: boolean;
    failureBehavior?: RuleBindingFailureBehavior;
};

export type CreateRuleDefinitionRequest = {
    name?: string;
    description?: string;
};

export type CurrentUserProfileDto = {
    id?: string;
    email?: string;
    fullName?: string;
    isActive?: boolean;
    language?: string | null;
    theme?: string | null;
    workspaceId?: string | null;
    workspaces?: Array<UserWorkspaceDto>;
};

export type DeleteRuleBindingRequest = {
    expectedRevision?: number;
};

export type EvaluateRuleBindingRequest = {
    context?: RuleContext;
    bindingRevision?: number | null;
};

export type HttpValidationProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    errors?: {
        [key: string]: Array<string>;
    };
    /**
     * Stable machine-readable problem code for client behavior and localization.
     */
    code?: string | null;
    /**
     * Optional field-level machine-readable validation codes keyed by JSON field name.
     */
    errorCodes?: {
        [key: string]: Array<string>;
    } | null;
    [key: string]: unknown;
};

export type InstallSolutionResponse = {
    operation?: SolutionOperationStatusDto;
    isRetry?: boolean;
};

export type InviteWorkspaceMemberDto = {
    outcome?: string;
    requestedRole?: string;
    invitation?: WorkspaceInvitationLifecycleDto;
};

export type InviteWorkspaceMemberRequest = {
    email?: string;
    requestedRole?: string;
};

export type KeyRequest = {
    expectedRevision?: number;
    publicJwk?: string;
};

export type LanguagePreferenceDto = {
    language?: string;
};

export type LegalVersionsDto = {
    termsVersion?: string;
    privacyVersion?: string;
};

export type MessageResponse = {
    message?: string;
};

export type ModuleNavigationAvailabilityDto = {
    availableContributionIds?: Array<string>;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    /**
     * Stable machine-readable problem code for client behavior and localization.
     */
    code?: string | null;
    /**
     * Optional field-level machine-readable validation codes keyed by JSON field name.
     */
    errorCodes?: {
        [key: string]: Array<string>;
    } | null;
    [key: string]: unknown;
};

export type ProductRoleAssignmentDto = {
    workspaceId?: string;
    subject?: SubjectReferenceDto;
    policyVersionId?: string;
    roleKey?: string;
    isActive?: boolean;
    revision?: number;
};

export type ProductRoleAssignmentResponse = {
    workspaceId?: string;
    subject?: SubjectReferenceDto;
    policyVersionId?: string;
    roleKey?: string;
    isActive?: boolean;
    revision?: number;
};

export type ProductRoleManagementResponse = {
    subjects?: Array<AssignableSubjectDto>;
    roles?: Array<ProductRoleOptionDto>;
    assignments?: Array<ProductRoleAssignmentDto>;
};

export type ProductRoleOptionDto = {
    policyVersionId?: string;
    policyKey?: string;
    roleKey?: string;
    displayName?: string;
    description?: string | null;
};

export type ProjectRuleAuthoringRequest = {
    source?: RuleAuthoringSourceDto;
    inputs?: Array<RuleInputDefinitionDto>;
    expressionLanguageVersion?: number;
    language?: string | null;
};

export type ProjectRuleConditionRequest = {
    expressionLanguageVersion?: number;
    inputs?: Array<RuleDraftInputDefinitionDto>;
    condition?: RuleConditionNodeDto;
    language?: string;
};

export type PublishBusinessObjectDefinitionRequest = {
    expectedRevision?: number;
};

export type PublishSolutionResponse = {
    version?: SolutionVersionSummaryDto;
    isRetry?: boolean;
};

export type RegisterUserRequest = {
    fullName?: string;
    email?: string;
    password?: string;
    passwordConfirmation?: string;
    acceptedTermsVersion?: string;
    acceptedPrivacyVersion?: string;
    preferredLanguage?: string | null;
};

export type ResendVerificationRequest = {
    email?: string;
};

export type RevisionRequest = {
    expectedRevision?: number;
};

export type RevokeProductRoleBody = {
    target?: SubjectReferenceDto;
    policyVersionId?: string;
    roleKey?: string;
    expectedRevision?: number;
};

export type RuleAuthoringCompletionDto = {
    label?: string;
    insertText?: string;
    kind?: string;
    start?: number;
    length?: number;
};

export type RuleAuthoringDiagnosticDto = {
    code?: string;
    message?: string;
    start?: number;
    length?: number;
};

export type RuleAuthoringProjectionDto = {
    condition?: RuleConditionNodeDto;
    formattedDsl?: string | null;
    explanation?: RuleExpressionDisplayNodeDto;
    diagnostics?: Array<RuleAuthoringDiagnosticDto>;
    readonly isValid?: boolean;
};

export type RuleAuthoringSourceDto = {
    text?: string | null;
    ast?: RuleConditionNodeDto;
};

export type RuleBindingDto = {
    id?: string;
    workspaceId?: string;
    definitionKey?: string;
    definitionVersion?: number;
    targetType?: string;
    targetId?: string;
    useCaseOrTrigger?: string;
    inputMappings?: {
        [key: string]: RuleInputMappingDto;
    };
    priority?: number;
    enabled?: boolean;
    failureBehavior?: RuleBindingFailureBehavior;
    revision?: number;
    createdAt?: string;
    updatedAt?: string;
};

export type RuleBindingFailureBehavior = 'FailClosed' | 'FailOpen';

export type RuleBindingUsageDto = {
    bindingId?: string;
    definitionKey?: string;
    definitionVersion?: number;
    targetType?: string;
    targetId?: string;
    useCaseOrTrigger?: string;
    priority?: number;
    enabled?: boolean;
    failureBehavior?: RuleBindingFailureBehavior;
    revision?: number;
};

export type RuleConditionNodeDto = {
    nodeId?: string;
    logicalOperator?: RuleLogicalOperator;
    predicateOperator?: RulePredicateOperator;
    left?: RuleOperandDto;
    right?: RuleOperandDto;
    children?: Array<RuleConditionNodeDto>;
};

export type RuleConditionProjectionDto = {
    condition?: RuleConditionNodeDto;
    display?: RuleExpressionDisplayNodeDto;
};

export type RuleContext = {
    values?: {
        [key: string]: RuleContextValue;
    };
};

export type RuleContextValue = {
    type?: RuleValueType;
    values?: Array<string>;
};

export type RuleDefinitionActionsDto = {
    canEditDraft?: boolean;
    canCreateVersion?: boolean;
    canActivateVersion?: boolean;
    canDeactivate?: boolean;
    canArchive?: boolean;
};

export type RuleDefinitionCollectionActionsDto = {
    canStartCreate?: boolean;
};

export type RuleDefinitionDetailDto = {
    definitionKey?: string;
    name?: string;
    description?: string;
    origin?: RuleOrigin;
    status?: RuleLifecycleStatus;
    expressionLanguageVersion?: number;
    revision?: number | null;
    latestVersion?: number | null;
    activeVersion?: number | null;
    inputs?: Array<RuleInputDefinitionDto>;
    output?: RuleOutputContractDto;
    condition?: RuleConditionNodeDto;
    versions?: Array<RuleDefinitionVersionDto>;
    createdAt?: string | null;
    updatedAt?: string | null;
    archivedAt?: string | null;
    actions?: RuleDefinitionActionsDto;
    documentation?: RuleReferenceDocumentationDto;
};

export type RuleDefinitionSummaryDto = {
    definitionKey?: string;
    name?: string;
    description?: string;
    origin?: RuleOrigin;
    status?: RuleLifecycleStatus;
    expressionLanguageVersion?: number;
    revision?: number | null;
    latestVersion?: number | null;
    activeVersion?: number | null;
    inputs?: Array<RuleInputDefinitionDto>;
    output?: RuleOutputContractDto;
    updatedAt?: string | null;
    actions?: RuleDefinitionActionsDto;
    documentation?: RuleReferenceDocumentationDto;
};

export type RuleDefinitionSummaryDtoPagedResult = {
    items: Array<RuleDefinitionSummaryDto>;
    totalCount: number;
    page: number;
    pageSize: number;
};

export type RuleDefinitionVersionDto = {
    version?: number;
    name?: string;
    description?: string;
    expressionLanguageVersion?: number;
    inputs?: Array<RuleInputDefinitionDto>;
    output?: RuleOutputContractDto;
    condition?: RuleConditionNodeDto;
    publishedBySubject?: SubjectReferenceDto;
    createdAt?: string;
};

export type RuleDraftInputDefinitionDto = {
    key?: string;
    label?: string;
    types?: Array<RuleValueType>;
    isRequired?: boolean;
    allowMultiple?: boolean;
    allowedValues?: Array<string>;
};

export type RuleEvaluationItemDto = {
    definitionKey?: string;
    definitionVersion?: number;
    isMatch?: boolean;
    diagnostics?: Array<RuleNodeDiagnosticDto>;
};

export type RuleEvaluationResult = {
    isSuccess?: boolean;
    items?: Array<RuleEvaluationItemDto>;
    correlationId?: string;
    errorCode?: string | null;
    error?: string | null;
};

export type RuleExpressionCardinality = 'Scalar' | 'Multiple' | 'Any';

export type RuleExpressionCardinalityDefinitionDto = {
    cardinality?: RuleExpressionCardinality;
    documentation?: RuleReferenceDocumentationDto;
};

export type RuleExpressionDisplayNodeDto = {
    nodeId?: string;
    tokens?: Array<RuleExpressionDisplayTokenDto>;
    children?: Array<RuleExpressionDisplayNodeDto>;
};

export type RuleExpressionDisplayTokenDto = {
    text?: string;
    referenceKind?: RuleExpressionReferenceKind;
    referenceKey?: string | null;
    isCode?: boolean;
};

export type RuleExpressionFunction = 'IsBlank' | 'Length' | 'Precision' | 'Scale' | 'Count' | 'MatchesPattern' | 'HasFormat' | 'ToDecimal';

export type RuleExpressionFunctionDefinitionDto = {
    function?: RuleExpressionFunction;
    parameters?: Array<RuleExpressionFunctionParameterDto>;
    returnType?: RuleValueType;
    returnCardinality?: RuleExpressionCardinality;
    documentation?: RuleReferenceDocumentationDto;
};

export type RuleExpressionFunctionParameterDto = {
    acceptedTypes?: Array<RuleValueType>;
    cardinality?: RuleExpressionCardinality;
};

export type RuleExpressionGuideDto = {
    expressionLanguageVersion?: number;
    totalResults?: number;
    sections?: Array<RuleExpressionGuideSectionDto>;
};

export type RuleExpressionGuideItemDto = {
    referenceKind?: RuleExpressionReferenceKind;
    referenceKey?: string;
    displayName?: SearchTextDto;
    summary?: SearchTextDto;
    usage?: SearchTextDto;
    examples?: Array<SearchTextDto>;
    detail?: SearchTextDto;
};

export type RuleExpressionGuideSectionDto = {
    key?: string;
    title?: string;
    description?: string;
    items?: Array<RuleExpressionGuideItemDto>;
};

export type RuleExpressionLanguageDto = {
    version?: number;
    operators?: Array<RulePredicateOperatorDefinitionDto>;
    functions?: Array<RuleExpressionFunctionDefinitionDto>;
    logicalOperators?: Array<RuleLogicalOperatorDefinitionDto>;
    operandKinds?: Array<RuleOperandKindDefinitionDto>;
    valueTypes?: Array<RuleValueTypeDefinitionDto>;
    cardinalities?: Array<RuleExpressionCardinalityDefinitionDto>;
    limitDefinitions?: Array<RuleExpressionLimitDefinitionDto>;
    limits?: RuleExpressionLimitsDto;
};

export type RuleExpressionLimitDefinitionDto = {
    key?: string;
    value?: number;
    documentation?: RuleReferenceDocumentationDto;
};

export type RuleExpressionLimitsDto = {
    maxDepth?: number;
    maxNodes?: number;
    maxFunctionCalls?: number;
    maxInputs?: number;
    maxExecutionSteps?: number;
};

export type RuleExpressionReferenceKind = 'LogicalOperator' | 'PredicateOperator' | 'Function' | 'Input' | 'Literal' | 'ValueType' | 'OperandKind' | 'Limit';

export type RuleExpressionValueShapeDto = {
    type?: RuleValueType;
    cardinality?: RuleExpressionCardinality;
};

export type RuleInputDefinitionDto = {
    key?: string;
    label?: string;
    types?: Array<RuleValueType>;
    isRequired?: boolean;
    allowMultiple?: boolean;
    allowedValues?: Array<string>;
};

export type RuleInputMappingDto = {
    kind?: RuleInputMappingKind;
    contextKey?: string | null;
    literalValues?: Array<string>;
};

export type RuleInputMappingKind = 'Context' | 'Literal';

export type RuleLifecycleStatus = 'Draft' | 'Inactive' | 'Active' | 'Archived';

export type RuleLogicalOperator = 'All' | 'Any' | 'Not';

export type RuleLogicalOperatorDefinitionDto = {
    operator?: RuleLogicalOperator;
    minimumChildren?: number;
    maximumChildren?: number | null;
    documentation?: RuleReferenceDocumentationDto;
};

export type RuleNodeDiagnosticDto = {
    nodeId?: string;
    isMatch?: boolean;
};

export type RuleOperandDto = {
    kind?: RuleOperandKind;
    reference?: string | null;
    literal?: RuleValueDto;
    function?: RuleExpressionFunction;
    arguments?: Array<RuleOperandDto> | null;
};

export type RuleOperandKind = 'Input' | 'Literal' | 'Function';

export type RuleOperandKindDefinitionDto = {
    kind?: RuleOperandKind;
    documentation?: RuleReferenceDocumentationDto;
};

export type RuleOrigin = 'BuiltIn' | 'Workspace';

export type RuleOutputContractDto = {
    type?: RuleValueType;
    cardinality?: RuleExpressionCardinality;
};

export type RulePredicateOperator = 'Equal' | 'NotEqual' | 'GreaterThan' | 'GreaterThanOrEqual' | 'LessThan' | 'LessThanOrEqual' | 'Contains' | 'StartsWith' | 'EndsWith' | 'IsNull' | 'IsNotNull';

export type RulePredicateOperatorDefinitionDto = {
    operator?: RulePredicateOperator;
    leftShapes?: Array<RuleExpressionValueShapeDto>;
    rightShapes?: Array<RuleExpressionValueShapeDto>;
    requiresMatchingTypes?: boolean;
    documentation?: RuleReferenceDocumentationDto;
};

export type RuleReferenceContentDto = {
    displayName?: string;
    summary?: string;
    usage?: string;
    examples?: Array<string>;
};

export type RuleReferenceDocumentationDto = {
    locales?: {
        [key: string]: RuleReferenceContentDto;
    };
};

export type RuleRevisionRequest = {
    expectedRevision?: number;
};

export type RuleSimulationResultDto = {
    definitionKey?: string;
    definitionVersion?: number | null;
    isMatch?: boolean;
    diagnostics?: Array<RuleNodeDiagnosticDto>;
    correlationId?: string;
};

export type RuleValueDto = {
    type?: RuleValueType;
    values?: Array<string>;
};

export type RuleValueType = 'Text' | 'Integer' | 'Decimal' | 'Date' | 'DateTime' | 'Boolean';

export type RuleValueTypeDefinitionDto = {
    type?: RuleValueType;
    documentation?: RuleReferenceDocumentationDto;
};

export type SaveBusinessObjectRecordRequest = {
    expectedRevision: number;
    values: {
        [key: string]: Array<string>;
    };
};

export type SaveRuleDefinitionDraftRequest = {
    expectedRevision?: number;
    name?: string;
    description?: string;
    inputs?: Array<RuleDraftInputDefinitionDto>;
    condition?: RuleConditionNodeDto;
};

export type SaveUnpublishedBusinessObjectDefinitionRequest = {
    expectedRevision?: number;
    name?: string;
    fields?: Array<BusinessObjectFieldDefinitionInput>;
};

export type SearchRuleExpressionGuideRequest = {
    expressionLanguageVersion?: number;
    definitionKey?: string | null;
    inputs?: Array<RuleInputDefinitionDto>;
    query?: string | null;
    language?: string;
};

export type SearchTextDto = {
    text?: string;
    segments?: Array<SearchTextSegmentDto>;
};

export type SearchTextSegmentDto = {
    text?: string;
    isMatch?: boolean;
};

export type ServiceIdentityDto = {
    id?: string;
    clientId?: string;
    workspaceId?: string;
    status?: string;
    workspaceGrantStatus?: string;
    revision?: number;
    keys?: Array<ServiceIdentityKeyDto>;
    subject?: SubjectReferenceDto;
};

export type ServiceIdentityKeyDto = {
    id?: string;
    kid?: string;
    thumbprint?: string;
    status?: string;
};

export type SignInNextStep = 'Dashboard';

export type SignInSessionEstablishedDto = {
    sessionEstablished?: boolean;
    nextStep?: SignInNextStep;
};

export type SignInUserRequest = {
    email?: string;
    password?: string;
};

export type SimulateRuleDraftRequest = {
    inputs?: {
        [key: string]: RuleValueDto;
    };
};

export type SimulateRuleVersionRequest = {
    inputs?: {
        [key: string]: RuleValueDto;
    };
};

export type SolutionComplianceStatus = 'Compliant' | 'Noncompliant';

export type SolutionComponentIdentityDto = {
    type?: string;
    key?: string;
};

export type SolutionComponentPlanDto = {
    type?: string;
    key?: string;
    sha256?: string;
    dependsOn?: Array<SolutionComponentIdentityDto>;
};

export type SolutionComponentStatusDto = {
    type?: string;
    key?: string;
    sha256?: string;
    status?: SolutionStepStatus;
    problemCode?: string | null;
};

export type SolutionInstallationStatusDto = {
    id?: string;
    workspaceId?: string;
    solutionVersionId?: string;
    operationId?: string | null;
    operationStatus?: SolutionOperationStatus;
    provisioningStatus?: SolutionProvisioningStatus;
    complianceStatus?: SolutionComplianceStatus;
    components?: Array<SolutionComponentStatusDto>;
    updatedAt?: string;
};

export type SolutionOperationStatus = 'Pending' | 'Running' | 'Failed' | 'Blocked' | 'Succeeded';

export type SolutionOperationStatusDto = {
    id?: string;
    installationId?: string;
    status?: SolutionOperationStatus;
    leaseEpoch?: number;
    problemCode?: string | null;
    steps?: Array<SolutionComponentStatusDto>;
    updatedAt?: string;
};

export type SolutionProvisioningStatus = 'Installing' | 'Installed' | 'Failed';

export type SolutionStepStatus = 'Pending' | 'Applying' | 'Confirmed' | 'Failed';

export type SolutionTrustStatus = 'Trusted' | 'Revoked' | 'Unknown';

export type SolutionVersionSummaryDto = {
    id?: string;
    solutionKey?: string;
    solutionVersion?: string;
    packageSha256?: string;
    axisOpenApiSha256?: string;
    publisherId?: string;
    publisherKeyId?: string;
    trustStatus?: SolutionTrustStatus;
    sourceRevision?: string;
    buildId?: string;
    builtAt?: string;
    sourceUri?: string;
    publishedAt?: string;
    components?: Array<SolutionComponentPlanDto>;
};

export type SubjectKind = 'Human' | 'Service';

export type SubjectReferenceDto = {
    kind: SubjectKind;
    subjectId: string;
};

export type SubmitBusinessObjectRecordRequest = {
    expectedRevision: number;
};

export type ThemePreferenceDto = {
    theme?: string;
};

export type UpdateRuleBindingRequest = {
    expectedRevision?: number;
    definitionKey?: string;
    definitionVersion?: number;
    targetType?: string;
    targetId?: string;
    useCaseOrTrigger?: string;
    inputMappings?: {
        [key: string]: RuleInputMappingDto;
    };
    priority?: number;
    enabled?: boolean;
    failureBehavior?: RuleBindingFailureBehavior;
};

export type UpdateUserLanguagePreferenceRequest = {
    language?: string;
};

export type UpdateUserThemePreferenceRequest = {
    theme?: string;
};

export type UserWorkspaceDto = {
    id?: string;
    name?: string;
    slug?: string;
    type?: string;
    isCurrent?: boolean;
};

export type VerifyEmailNextStep = 'Dashboard';

export type VerifyEmailRequest = {
    token?: string;
};

export type VerifyEmailSessionEstablishedDto = {
    sessionEstablished?: boolean;
    nextStep?: VerifyEmailNextStep;
};

export type WorkspaceInvitationLifecycleDto = {
    invitationId?: string;
    recipientEmail?: string | null;
    requestedRole?: string;
    status?: string;
    deliveryStatus?: string;
    createdAt?: string;
    expiresAt?: string;
    revision?: number;
};

export type WorkspaceInvitationPageDto = {
    items?: Array<WorkspaceInvitationLifecycleDto>;
    page?: number;
    pageSize?: number;
    totalCount?: number;
};

export type WorkspaceProductBuilderDto = {
    userId?: string;
    displayName?: string;
    email?: string;
    workspaceRole?: string;
    isProductBuilder?: boolean;
    membershipRevision?: number;
    canChange?: boolean;
};

export type RuleAuthoringProjectionDtoWritable = {
    condition?: RuleConditionNodeDto;
    formattedDsl?: string | null;
    explanation?: RuleExpressionDisplayNodeDto;
    diagnostics?: Array<RuleAuthoringDiagnosticDto>;
};

export type GetModuleNavigationAvailabilityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/module-navigation';
};

export type GetModuleNavigationAvailabilityErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
};

export type GetModuleNavigationAvailabilityError = GetModuleNavigationAvailabilityErrors[keyof GetModuleNavigationAvailabilityErrors];

export type GetModuleNavigationAvailabilityResponses = {
    /**
     * OK
     */
    200: ModuleNavigationAvailabilityDto;
};

export type GetModuleNavigationAvailabilityResponse = GetModuleNavigationAvailabilityResponses[keyof GetModuleNavigationAvailabilityResponses];

export type AssignProductRoleData = {
    body: AssignProductRoleBody;
    headers: {
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/api/product-role-assignments/assign';
};

export type AssignProductRoleErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type AssignProductRoleError = AssignProductRoleErrors[keyof AssignProductRoleErrors];

export type AssignProductRoleResponses = {
    /**
     * OK
     */
    200: ProductRoleAssignmentResponse;
};

export type AssignProductRoleResponse = AssignProductRoleResponses[keyof AssignProductRoleResponses];

export type RevokeProductRoleData = {
    body: RevokeProductRoleBody;
    headers: {
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/api/product-role-assignments/revoke';
};

export type RevokeProductRoleErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type RevokeProductRoleError = RevokeProductRoleErrors[keyof RevokeProductRoleErrors];

export type RevokeProductRoleResponses = {
    /**
     * OK
     */
    200: ProductRoleAssignmentResponse;
};

export type RevokeProductRoleResponse = RevokeProductRoleResponses[keyof RevokeProductRoleResponses];

export type ListProductRoleAssignmentsData = {
    body?: never;
    path?: never;
    query?: {
        language?: string;
    };
    url: '/api/product-role-assignments';
};

export type ListProductRoleAssignmentsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type ListProductRoleAssignmentsError = ListProductRoleAssignmentsErrors[keyof ListProductRoleAssignmentsErrors];

export type ListProductRoleAssignmentsResponses = {
    /**
     * OK
     */
    200: ProductRoleManagementResponse;
};

export type ListProductRoleAssignmentsResponse = ListProductRoleAssignmentsResponses[keyof ListProductRoleAssignmentsResponses];

export type ListBusinessObjectRecordsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
        objectKey?: string;
    };
    url: '/api/business-object-records';
};

export type ListBusinessObjectRecordsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type ListBusinessObjectRecordsError = ListBusinessObjectRecordsErrors[keyof ListBusinessObjectRecordsErrors];

export type ListBusinessObjectRecordsResponses = {
    /**
     * OK
     */
    200: BusinessObjectRecordListItemDtoPagedResult;
};

export type ListBusinessObjectRecordsResponse = ListBusinessObjectRecordsResponses[keyof ListBusinessObjectRecordsResponses];

export type CreateBusinessObjectRecordData = {
    body: CreateBusinessObjectRecordRequest;
    path: {
        objectKey: string;
    };
    query?: never;
    url: '/api/business-object-records/{objectKey}';
};

export type CreateBusinessObjectRecordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Unprocessable Content
     */
    422: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type CreateBusinessObjectRecordError = CreateBusinessObjectRecordErrors[keyof CreateBusinessObjectRecordErrors];

export type CreateBusinessObjectRecordResponses = {
    /**
     * Created
     */
    201: BusinessObjectRecordDetailDto;
};

export type CreateBusinessObjectRecordResponse = CreateBusinessObjectRecordResponses[keyof CreateBusinessObjectRecordResponses];

export type GetBusinessObjectRecordData = {
    body?: never;
    path: {
        recordId: string;
    };
    query?: never;
    url: '/api/business-object-records/{recordId}';
};

export type GetBusinessObjectRecordErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type GetBusinessObjectRecordError = GetBusinessObjectRecordErrors[keyof GetBusinessObjectRecordErrors];

export type GetBusinessObjectRecordResponses = {
    /**
     * OK
     */
    200: BusinessObjectRecordDetailDto;
};

export type GetBusinessObjectRecordResponse = GetBusinessObjectRecordResponses[keyof GetBusinessObjectRecordResponses];

export type SaveBusinessObjectRecordData = {
    body: SaveBusinessObjectRecordRequest;
    path: {
        recordId: string;
    };
    query?: never;
    url: '/api/business-object-records/{recordId}';
};

export type SaveBusinessObjectRecordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Unprocessable Content
     */
    422: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type SaveBusinessObjectRecordError = SaveBusinessObjectRecordErrors[keyof SaveBusinessObjectRecordErrors];

export type SaveBusinessObjectRecordResponses = {
    /**
     * OK
     */
    200: BusinessObjectRecordDetailDto;
};

export type SaveBusinessObjectRecordResponse = SaveBusinessObjectRecordResponses[keyof SaveBusinessObjectRecordResponses];

export type SubmitBusinessObjectRecordData = {
    body: SubmitBusinessObjectRecordRequest;
    path: {
        recordId: string;
    };
    query?: never;
    url: '/api/business-object-records/{recordId}/submit';
};

export type SubmitBusinessObjectRecordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Unprocessable Content
     */
    422: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type SubmitBusinessObjectRecordError = SubmitBusinessObjectRecordErrors[keyof SubmitBusinessObjectRecordErrors];

export type SubmitBusinessObjectRecordResponses = {
    /**
     * OK
     */
    200: BusinessObjectRecordSubmitResultDto;
};

export type SubmitBusinessObjectRecordResponse = SubmitBusinessObjectRecordResponses[keyof SubmitBusinessObjectRecordResponses];

export type ListBusinessObjectDefinitionsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
        query?: string;
        language?: string;
    };
    url: '/api/business-object-definitions';
};

export type ListBusinessObjectDefinitionsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type ListBusinessObjectDefinitionsError = ListBusinessObjectDefinitionsErrors[keyof ListBusinessObjectDefinitionsErrors];

export type ListBusinessObjectDefinitionsResponses = {
    /**
     * OK
     */
    200: BusinessObjectDefinitionListItemDtoPagedResult;
};

export type ListBusinessObjectDefinitionsResponse = ListBusinessObjectDefinitionsResponses[keyof ListBusinessObjectDefinitionsResponses];

export type CreateBusinessObjectDefinitionData = {
    body: CreateBusinessObjectDefinitionRequest;
    path?: never;
    query?: never;
    url: '/api/business-object-definitions';
};

export type CreateBusinessObjectDefinitionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type CreateBusinessObjectDefinitionError = CreateBusinessObjectDefinitionErrors[keyof CreateBusinessObjectDefinitionErrors];

export type CreateBusinessObjectDefinitionResponses = {
    /**
     * Created
     */
    201: BusinessObjectDefinitionDetailDto;
};

export type CreateBusinessObjectDefinitionResponse = CreateBusinessObjectDefinitionResponses[keyof CreateBusinessObjectDefinitionResponses];

export type GetBusinessObjectDefinitionCollectionActionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/business-object-definitions/actions';
};

export type GetBusinessObjectDefinitionCollectionActionsErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type GetBusinessObjectDefinitionCollectionActionsError = GetBusinessObjectDefinitionCollectionActionsErrors[keyof GetBusinessObjectDefinitionCollectionActionsErrors];

export type GetBusinessObjectDefinitionCollectionActionsResponses = {
    /**
     * OK
     */
    200: BusinessObjectDefinitionCollectionActionsDto;
};

export type GetBusinessObjectDefinitionCollectionActionsResponse = GetBusinessObjectDefinitionCollectionActionsResponses[keyof GetBusinessObjectDefinitionCollectionActionsResponses];

export type GetBusinessObjectDefinitionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/business-object-definitions/{id}';
};

export type GetBusinessObjectDefinitionErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type GetBusinessObjectDefinitionError = GetBusinessObjectDefinitionErrors[keyof GetBusinessObjectDefinitionErrors];

export type GetBusinessObjectDefinitionResponses = {
    /**
     * OK
     */
    200: BusinessObjectDefinitionDetailDto;
};

export type GetBusinessObjectDefinitionResponse = GetBusinessObjectDefinitionResponses[keyof GetBusinessObjectDefinitionResponses];

export type SaveUnpublishedBusinessObjectDefinitionData = {
    body: SaveUnpublishedBusinessObjectDefinitionRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/business-object-definitions/{id}/unpublished';
};

export type SaveUnpublishedBusinessObjectDefinitionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type SaveUnpublishedBusinessObjectDefinitionError = SaveUnpublishedBusinessObjectDefinitionErrors[keyof SaveUnpublishedBusinessObjectDefinitionErrors];

export type SaveUnpublishedBusinessObjectDefinitionResponses = {
    /**
     * OK
     */
    200: BusinessObjectDefinitionDetailDto;
};

export type SaveUnpublishedBusinessObjectDefinitionResponse = SaveUnpublishedBusinessObjectDefinitionResponses[keyof SaveUnpublishedBusinessObjectDefinitionResponses];

export type PublishBusinessObjectDefinitionData = {
    body: PublishBusinessObjectDefinitionRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/business-object-definitions/{id}/publish';
};

export type PublishBusinessObjectDefinitionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type PublishBusinessObjectDefinitionError = PublishBusinessObjectDefinitionErrors[keyof PublishBusinessObjectDefinitionErrors];

export type PublishBusinessObjectDefinitionResponses = {
    /**
     * OK
     */
    200: BusinessObjectDefinitionDetailDto;
};

export type PublishBusinessObjectDefinitionResponse = PublishBusinessObjectDefinitionResponses[keyof PublishBusinessObjectDefinitionResponses];

export type GetLegalVersionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/legal/versions';
};

export type GetLegalVersionsResponses = {
    /**
     * OK
     */
    200: LegalVersionsDto;
};

export type GetLegalVersionsResponse = GetLegalVersionsResponses[keyof GetLegalVersionsResponses];

export type GetBrowserSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/session';
};

export type GetBrowserSessionResponses = {
    /**
     * OK
     */
    200: AxisBrowserSessionDto;
};

export type GetBrowserSessionResponse = GetBrowserSessionResponses[keyof GetBrowserSessionResponses];

export type SignInUserData = {
    body: SignInUserRequest;
    path?: never;
    query?: never;
    url: '/api/auth/sign-in';
};

export type SignInUserErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unprocessable Content
     */
    422: ProblemDetails;
    /**
     * Too Many Requests
     */
    429: ProblemDetails;
};

export type SignInUserError = SignInUserErrors[keyof SignInUserErrors];

export type SignInUserResponses = {
    /**
     * OK
     */
    200: SignInSessionEstablishedDto;
};

export type SignInUserResponse = SignInUserResponses[keyof SignInUserResponses];

export type VerifyEmailData = {
    body: VerifyEmailRequest;
    path?: never;
    query?: never;
    url: '/api/auth/verify-email';
};

export type VerifyEmailErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type VerifyEmailError = VerifyEmailErrors[keyof VerifyEmailErrors];

export type VerifyEmailResponses = {
    /**
     * OK
     */
    200: VerifyEmailSessionEstablishedDto;
};

export type VerifyEmailResponse = VerifyEmailResponses[keyof VerifyEmailResponses];

export type ResendEmailVerificationData = {
    body: ResendVerificationRequest;
    path?: never;
    query?: never;
    url: '/api/auth/resend-verification';
};

export type ResendEmailVerificationErrors = {
    /**
     * Too Many Requests
     */
    429: ProblemDetails;
};

export type ResendEmailVerificationError = ResendEmailVerificationErrors[keyof ResendEmailVerificationErrors];

export type ResendEmailVerificationResponses = {
    /**
     * No Content
     */
    204: void;
};

export type ResendEmailVerificationResponse = ResendEmailVerificationResponses[keyof ResendEmailVerificationResponses];

export type SignOutUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/sign-out';
};

export type SignOutUserResponses = {
    /**
     * No Content
     */
    204: void;
};

export type SignOutUserResponse = SignOutUserResponses[keyof SignOutUserResponses];

export type RegisterUserData = {
    body: RegisterUserRequest;
    path?: never;
    query?: never;
    url: '/api/users/register';
};

export type RegisterUserErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type RegisterUserError = RegisterUserErrors[keyof RegisterUserErrors];

export type RegisterUserResponses = {
    /**
     * OK
     */
    200: MessageResponse;
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type GetMeErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * OK
     */
    200: CurrentUserProfileDto;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type UpdateLanguagePreferenceData = {
    body: UpdateUserLanguagePreferenceRequest;
    path?: never;
    query?: never;
    url: '/api/users/me/preferences/language';
};

export type UpdateLanguagePreferenceErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateLanguagePreferenceError = UpdateLanguagePreferenceErrors[keyof UpdateLanguagePreferenceErrors];

export type UpdateLanguagePreferenceResponses = {
    /**
     * OK
     */
    200: LanguagePreferenceDto;
};

export type UpdateLanguagePreferenceResponse = UpdateLanguagePreferenceResponses[keyof UpdateLanguagePreferenceResponses];

export type UpdateThemePreferenceData = {
    body: UpdateUserThemePreferenceRequest;
    path?: never;
    query?: never;
    url: '/api/users/me/preferences/theme';
};

export type UpdateThemePreferenceErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateThemePreferenceError = UpdateThemePreferenceErrors[keyof UpdateThemePreferenceErrors];

export type UpdateThemePreferenceResponses = {
    /**
     * OK
     */
    200: ThemePreferenceDto;
};

export type UpdateThemePreferenceResponse = UpdateThemePreferenceResponses[keyof UpdateThemePreferenceResponses];

export type CreateOrganizationWorkspaceData = {
    body: CreateOrganizationWorkspaceRequest;
    headers: {
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/api/organizations';
};

export type CreateOrganizationWorkspaceErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Unprocessable Content
     */
    422: ProblemDetails;
};

export type CreateOrganizationWorkspaceError = CreateOrganizationWorkspaceErrors[keyof CreateOrganizationWorkspaceErrors];

export type CreateOrganizationWorkspaceResponses = {
    /**
     * Created
     */
    201: CreateOrganizationWorkspaceDto;
};

export type CreateOrganizationWorkspaceResponse = CreateOrganizationWorkspaceResponses[keyof CreateOrganizationWorkspaceResponses];

export type ListWorkspaceInvitationsData = {
    body?: never;
    path?: never;
    query: {
        page: number;
        pageSize: number;
    };
    url: '/api/workspace-invitations';
};

export type ListWorkspaceInvitationsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type ListWorkspaceInvitationsError = ListWorkspaceInvitationsErrors[keyof ListWorkspaceInvitationsErrors];

export type ListWorkspaceInvitationsResponses = {
    /**
     * OK
     */
    200: WorkspaceInvitationPageDto;
};

export type ListWorkspaceInvitationsResponse = ListWorkspaceInvitationsResponses[keyof ListWorkspaceInvitationsResponses];

export type InviteWorkspaceMemberData = {
    body: InviteWorkspaceMemberRequest;
    path?: never;
    query?: never;
    url: '/api/workspace-invitations';
};

export type InviteWorkspaceMemberErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Unprocessable Content
     */
    422: ProblemDetails;
    /**
     * Too Many Requests
     */
    429: ProblemDetails;
};

export type InviteWorkspaceMemberError = InviteWorkspaceMemberErrors[keyof InviteWorkspaceMemberErrors];

export type InviteWorkspaceMemberResponses = {
    /**
     * OK
     */
    200: InviteWorkspaceMemberDto;
    /**
     * Created
     */
    201: InviteWorkspaceMemberDto;
};

export type InviteWorkspaceMemberResponse = InviteWorkspaceMemberResponses[keyof InviteWorkspaceMemberResponses];

export type ResendWorkspaceInvitationData = {
    body: ChangeWorkspaceInvitationRequest;
    path: {
        invitationId: string;
    };
    query?: never;
    url: '/api/workspace-invitations/{invitationId}/resend';
};

export type ResendWorkspaceInvitationErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Too Many Requests
     */
    429: ProblemDetails;
};

export type ResendWorkspaceInvitationError = ResendWorkspaceInvitationErrors[keyof ResendWorkspaceInvitationErrors];

export type ResendWorkspaceInvitationResponses = {
    /**
     * OK
     */
    200: WorkspaceInvitationLifecycleDto;
};

export type ResendWorkspaceInvitationResponse = ResendWorkspaceInvitationResponses[keyof ResendWorkspaceInvitationResponses];

export type RevokeWorkspaceInvitationData = {
    body: ChangeWorkspaceInvitationRequest;
    path: {
        invitationId: string;
    };
    query?: never;
    url: '/api/workspace-invitations/{invitationId}/revoke';
};

export type RevokeWorkspaceInvitationErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type RevokeWorkspaceInvitationError = RevokeWorkspaceInvitationErrors[keyof RevokeWorkspaceInvitationErrors];

export type RevokeWorkspaceInvitationResponses = {
    /**
     * OK
     */
    200: WorkspaceInvitationLifecycleDto;
};

export type RevokeWorkspaceInvitationResponse = RevokeWorkspaceInvitationResponses[keyof RevokeWorkspaceInvitationResponses];

export type ListWorkspaceProductBuildersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/workspace-product-builders';
};

export type ListWorkspaceProductBuildersErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type ListWorkspaceProductBuildersError = ListWorkspaceProductBuildersErrors[keyof ListWorkspaceProductBuildersErrors];

export type ListWorkspaceProductBuildersResponses = {
    /**
     * OK
     */
    200: Array<WorkspaceProductBuilderDto>;
};

export type ListWorkspaceProductBuildersResponse = ListWorkspaceProductBuildersResponses[keyof ListWorkspaceProductBuildersResponses];

export type GrantWorkspaceProductBuilderData = {
    body: ChangeWorkspaceProductBuilderRequest;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/workspace-product-builders/{userId}/grant';
};

export type GrantWorkspaceProductBuilderErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type GrantWorkspaceProductBuilderError = GrantWorkspaceProductBuilderErrors[keyof GrantWorkspaceProductBuilderErrors];

export type GrantWorkspaceProductBuilderResponses = {
    /**
     * OK
     */
    200: WorkspaceProductBuilderDto;
};

export type GrantWorkspaceProductBuilderResponse = GrantWorkspaceProductBuilderResponses[keyof GrantWorkspaceProductBuilderResponses];

export type RevokeWorkspaceProductBuilderData = {
    body: ChangeWorkspaceProductBuilderRequest;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/workspace-product-builders/{userId}/revoke';
};

export type RevokeWorkspaceProductBuilderErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type RevokeWorkspaceProductBuilderError = RevokeWorkspaceProductBuilderErrors[keyof RevokeWorkspaceProductBuilderErrors];

export type RevokeWorkspaceProductBuilderResponses = {
    /**
     * OK
     */
    200: WorkspaceProductBuilderDto;
};

export type RevokeWorkspaceProductBuilderResponse = RevokeWorkspaceProductBuilderResponses[keyof RevokeWorkspaceProductBuilderResponses];

export type ListServiceIdentitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/service-identities';
};

export type ListServiceIdentitiesErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetails;
};

export type ListServiceIdentitiesError = ListServiceIdentitiesErrors[keyof ListServiceIdentitiesErrors];

export type ListServiceIdentitiesResponses = {
    /**
     * OK
     */
    200: Array<ServiceIdentityDto>;
};

export type ListServiceIdentitiesResponse = ListServiceIdentitiesResponses[keyof ListServiceIdentitiesResponses];

export type CreateServiceIdentityData = {
    body: CreateRequest;
    path?: never;
    query?: never;
    url: '/api/service-identities';
};

export type CreateServiceIdentityErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type CreateServiceIdentityError = CreateServiceIdentityErrors[keyof CreateServiceIdentityErrors];

export type CreateServiceIdentityResponses = {
    /**
     * OK
     */
    200: ServiceIdentityDto;
};

export type CreateServiceIdentityResponse = CreateServiceIdentityResponses[keyof CreateServiceIdentityResponses];

export type GetServiceIdentityData = {
    body?: never;
    path: {
        serviceIdentityId: string;
    };
    query?: never;
    url: '/api/service-identities/{serviceIdentityId}';
};

export type GetServiceIdentityErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetServiceIdentityError = GetServiceIdentityErrors[keyof GetServiceIdentityErrors];

export type GetServiceIdentityResponses = {
    /**
     * OK
     */
    200: ServiceIdentityDto;
};

export type GetServiceIdentityResponse = GetServiceIdentityResponses[keyof GetServiceIdentityResponses];

export type AddServiceIdentityKeyData = {
    body: KeyRequest;
    path: {
        serviceIdentityId: string;
    };
    query?: never;
    url: '/api/service-identities/{serviceIdentityId}/keys';
};

export type AddServiceIdentityKeyErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type AddServiceIdentityKeyError = AddServiceIdentityKeyErrors[keyof AddServiceIdentityKeyErrors];

export type AddServiceIdentityKeyResponses = {
    /**
     * OK
     */
    200: ServiceIdentityDto;
};

export type AddServiceIdentityKeyResponse = AddServiceIdentityKeyResponses[keyof AddServiceIdentityKeyResponses];

export type RevokeServiceIdentityKeyData = {
    body: RevisionRequest;
    path: {
        serviceIdentityId: string;
        keyId: string;
    };
    query?: never;
    url: '/api/service-identities/{serviceIdentityId}/keys/{keyId}/revoke';
};

export type RevokeServiceIdentityKeyErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type RevokeServiceIdentityKeyError = RevokeServiceIdentityKeyErrors[keyof RevokeServiceIdentityKeyErrors];

export type RevokeServiceIdentityKeyResponses = {
    /**
     * OK
     */
    200: ServiceIdentityDto;
};

export type RevokeServiceIdentityKeyResponse = RevokeServiceIdentityKeyResponses[keyof RevokeServiceIdentityKeyResponses];

export type RevokeServiceIdentityData = {
    body: RevisionRequest;
    path: {
        serviceIdentityId: string;
    };
    query?: never;
    url: '/api/service-identities/{serviceIdentityId}/revoke';
};

export type RevokeServiceIdentityErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type RevokeServiceIdentityError = RevokeServiceIdentityErrors[keyof RevokeServiceIdentityErrors];

export type RevokeServiceIdentityResponses = {
    /**
     * OK
     */
    200: ServiceIdentityDto;
};

export type RevokeServiceIdentityResponse = RevokeServiceIdentityResponses[keyof RevokeServiceIdentityResponses];

export type ListRuleBindingUsageData = {
    body?: never;
    path: {
        definitionKey: string;
    };
    query: {
        version: number;
    };
    url: '/api/rules/{definitionKey}/bindings';
};

export type ListRuleBindingUsageErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type ListRuleBindingUsageError = ListRuleBindingUsageErrors[keyof ListRuleBindingUsageErrors];

export type ListRuleBindingUsageResponses = {
    /**
     * OK
     */
    200: Array<RuleBindingUsageDto>;
};

export type ListRuleBindingUsageResponse = ListRuleBindingUsageResponses[keyof ListRuleBindingUsageResponses];

export type ListRuleDefinitionsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
        origin?: RuleOrigin;
        status?: RuleLifecycleStatus;
        query?: string;
        language?: string;
    };
    url: '/api/rules';
};

export type ListRuleDefinitionsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type ListRuleDefinitionsError = ListRuleDefinitionsErrors[keyof ListRuleDefinitionsErrors];

export type ListRuleDefinitionsResponses = {
    /**
     * OK
     */
    200: RuleDefinitionSummaryDtoPagedResult;
};

export type ListRuleDefinitionsResponse = ListRuleDefinitionsResponses[keyof ListRuleDefinitionsResponses];

export type CreateRuleDefinitionData = {
    body: CreateRuleDefinitionRequest;
    path?: never;
    query?: never;
    url: '/api/rules';
};

export type CreateRuleDefinitionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type CreateRuleDefinitionError = CreateRuleDefinitionErrors[keyof CreateRuleDefinitionErrors];

export type CreateRuleDefinitionResponses = {
    /**
     * Created
     */
    201: RuleDefinitionDetailDto;
};

export type CreateRuleDefinitionResponse = CreateRuleDefinitionResponses[keyof CreateRuleDefinitionResponses];

export type GetRuleDefinitionCollectionActionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rules/actions';
};

export type GetRuleDefinitionCollectionActionsErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type GetRuleDefinitionCollectionActionsError = GetRuleDefinitionCollectionActionsErrors[keyof GetRuleDefinitionCollectionActionsErrors];

export type GetRuleDefinitionCollectionActionsResponses = {
    /**
     * OK
     */
    200: RuleDefinitionCollectionActionsDto;
};

export type GetRuleDefinitionCollectionActionsResponse = GetRuleDefinitionCollectionActionsResponses[keyof GetRuleDefinitionCollectionActionsResponses];

export type GetRuleExpressionLanguageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rules/expression-language';
};

export type GetRuleExpressionLanguageErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type GetRuleExpressionLanguageError = GetRuleExpressionLanguageErrors[keyof GetRuleExpressionLanguageErrors];

export type GetRuleExpressionLanguageResponses = {
    /**
     * OK
     */
    200: RuleExpressionLanguageDto;
};

export type GetRuleExpressionLanguageResponse = GetRuleExpressionLanguageResponses[keyof GetRuleExpressionLanguageResponses];

export type ProjectRuleConditionData = {
    body: ProjectRuleConditionRequest;
    path?: never;
    query?: never;
    url: '/api/rules/condition/project';
};

export type ProjectRuleConditionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type ProjectRuleConditionError = ProjectRuleConditionErrors[keyof ProjectRuleConditionErrors];

export type ProjectRuleConditionResponses = {
    /**
     * OK
     */
    200: RuleConditionProjectionDto;
};

export type ProjectRuleConditionResponse = ProjectRuleConditionResponses[keyof ProjectRuleConditionResponses];

export type SearchRuleExpressionGuideData = {
    body: SearchRuleExpressionGuideRequest;
    path?: never;
    query?: never;
    url: '/api/rules/expression-language/guide';
};

export type SearchRuleExpressionGuideErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type SearchRuleExpressionGuideError = SearchRuleExpressionGuideErrors[keyof SearchRuleExpressionGuideErrors];

export type SearchRuleExpressionGuideResponses = {
    /**
     * OK
     */
    200: RuleExpressionGuideDto;
};

export type SearchRuleExpressionGuideResponse = SearchRuleExpressionGuideResponses[keyof SearchRuleExpressionGuideResponses];

export type GetRuleDefinitionData = {
    body?: never;
    path: {
        definitionKey: string;
    };
    query?: never;
    url: '/api/rules/{definitionKey}';
};

export type GetRuleDefinitionErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type GetRuleDefinitionError = GetRuleDefinitionErrors[keyof GetRuleDefinitionErrors];

export type GetRuleDefinitionResponses = {
    /**
     * OK
     */
    200: RuleDefinitionDetailDto;
};

export type GetRuleDefinitionResponse = GetRuleDefinitionResponses[keyof GetRuleDefinitionResponses];

export type SaveRuleDefinitionDraftData = {
    body: SaveRuleDefinitionDraftRequest;
    path: {
        definitionKey: string;
    };
    query?: never;
    url: '/api/rules/{definitionKey}/draft';
};

export type SaveRuleDefinitionDraftErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type SaveRuleDefinitionDraftError = SaveRuleDefinitionDraftErrors[keyof SaveRuleDefinitionDraftErrors];

export type SaveRuleDefinitionDraftResponses = {
    /**
     * OK
     */
    200: RuleDefinitionDetailDto;
};

export type SaveRuleDefinitionDraftResponse = SaveRuleDefinitionDraftResponses[keyof SaveRuleDefinitionDraftResponses];

export type CreateRuleDefinitionVersionData = {
    body: RuleRevisionRequest;
    path: {
        definitionKey: string;
    };
    query?: never;
    url: '/api/rules/{definitionKey}/versions';
};

export type CreateRuleDefinitionVersionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type CreateRuleDefinitionVersionError = CreateRuleDefinitionVersionErrors[keyof CreateRuleDefinitionVersionErrors];

export type CreateRuleDefinitionVersionResponses = {
    /**
     * OK
     */
    200: RuleDefinitionDetailDto;
};

export type CreateRuleDefinitionVersionResponse = CreateRuleDefinitionVersionResponses[keyof CreateRuleDefinitionVersionResponses];

export type DeactivateRuleDefinitionData = {
    body: RuleRevisionRequest;
    path: {
        definitionKey: string;
    };
    query?: never;
    url: '/api/rules/{definitionKey}/active-version';
};

export type DeactivateRuleDefinitionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type DeactivateRuleDefinitionError = DeactivateRuleDefinitionErrors[keyof DeactivateRuleDefinitionErrors];

export type DeactivateRuleDefinitionResponses = {
    /**
     * OK
     */
    200: RuleDefinitionDetailDto;
};

export type DeactivateRuleDefinitionResponse = DeactivateRuleDefinitionResponses[keyof DeactivateRuleDefinitionResponses];

export type ActivateRuleDefinitionVersionData = {
    body: ActivateRuleDefinitionVersionRequest;
    path: {
        definitionKey: string;
    };
    query?: never;
    url: '/api/rules/{definitionKey}/active-version';
};

export type ActivateRuleDefinitionVersionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type ActivateRuleDefinitionVersionError = ActivateRuleDefinitionVersionErrors[keyof ActivateRuleDefinitionVersionErrors];

export type ActivateRuleDefinitionVersionResponses = {
    /**
     * OK
     */
    200: RuleDefinitionDetailDto;
};

export type ActivateRuleDefinitionVersionResponse = ActivateRuleDefinitionVersionResponses[keyof ActivateRuleDefinitionVersionResponses];

export type ArchiveRuleDefinitionData = {
    body: RuleRevisionRequest;
    path: {
        definitionKey: string;
    };
    query?: never;
    url: '/api/rules/{definitionKey}/archive';
};

export type ArchiveRuleDefinitionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type ArchiveRuleDefinitionError = ArchiveRuleDefinitionErrors[keyof ArchiveRuleDefinitionErrors];

export type ArchiveRuleDefinitionResponses = {
    /**
     * OK
     */
    200: RuleDefinitionDetailDto;
};

export type ArchiveRuleDefinitionResponse = ArchiveRuleDefinitionResponses[keyof ArchiveRuleDefinitionResponses];

export type SimulateRuleDefinitionDraftData = {
    body: SimulateRuleDraftRequest;
    path: {
        definitionKey: string;
    };
    query?: never;
    url: '/api/rules/{definitionKey}/draft/simulate';
};

export type SimulateRuleDefinitionDraftErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type SimulateRuleDefinitionDraftError = SimulateRuleDefinitionDraftErrors[keyof SimulateRuleDefinitionDraftErrors];

export type SimulateRuleDefinitionDraftResponses = {
    /**
     * OK
     */
    200: RuleSimulationResultDto;
};

export type SimulateRuleDefinitionDraftResponse = SimulateRuleDefinitionDraftResponses[keyof SimulateRuleDefinitionDraftResponses];

export type SimulateRuleDefinitionVersionData = {
    body: SimulateRuleVersionRequest;
    path: {
        definitionKey: string;
        version: number;
    };
    query?: never;
    url: '/api/rules/{definitionKey}/versions/{version}/simulate';
};

export type SimulateRuleDefinitionVersionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type SimulateRuleDefinitionVersionError = SimulateRuleDefinitionVersionErrors[keyof SimulateRuleDefinitionVersionErrors];

export type SimulateRuleDefinitionVersionResponses = {
    /**
     * OK
     */
    200: RuleSimulationResultDto;
};

export type SimulateRuleDefinitionVersionResponse = SimulateRuleDefinitionVersionResponses[keyof SimulateRuleDefinitionVersionResponses];

export type ProjectRuleAuthoringData = {
    body: ProjectRuleAuthoringRequest;
    path?: never;
    query?: never;
    url: '/api/rules/authoring/project';
};

export type ProjectRuleAuthoringErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type ProjectRuleAuthoringError = ProjectRuleAuthoringErrors[keyof ProjectRuleAuthoringErrors];

export type ProjectRuleAuthoringResponses = {
    /**
     * OK
     */
    200: RuleAuthoringProjectionDto;
};

export type ProjectRuleAuthoringResponse = ProjectRuleAuthoringResponses[keyof ProjectRuleAuthoringResponses];

export type CompleteRuleAuthoringData = {
    body: CompleteRuleAuthoringRequest;
    path?: never;
    query?: never;
    url: '/api/rules/authoring/complete';
};

export type CompleteRuleAuthoringErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type CompleteRuleAuthoringError = CompleteRuleAuthoringErrors[keyof CompleteRuleAuthoringErrors];

export type CompleteRuleAuthoringResponses = {
    /**
     * OK
     */
    200: Array<RuleAuthoringCompletionDto>;
};

export type CompleteRuleAuthoringResponse = CompleteRuleAuthoringResponses[keyof CompleteRuleAuthoringResponses];

export type CreateRuleBindingData = {
    body: CreateRuleBindingRequest;
    path?: never;
    query?: never;
    url: '/api/rule-bindings';
};

export type CreateRuleBindingErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type CreateRuleBindingError = CreateRuleBindingErrors[keyof CreateRuleBindingErrors];

export type CreateRuleBindingResponses = {
    /**
     * Created
     */
    201: RuleBindingDto;
};

export type CreateRuleBindingResponse = CreateRuleBindingResponses[keyof CreateRuleBindingResponses];

export type DeleteRuleBindingData = {
    body: DeleteRuleBindingRequest;
    path: {
        bindingId: string;
    };
    query?: never;
    url: '/api/rule-bindings/{bindingId}';
};

export type DeleteRuleBindingErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type DeleteRuleBindingError = DeleteRuleBindingErrors[keyof DeleteRuleBindingErrors];

export type DeleteRuleBindingResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRuleBindingResponse = DeleteRuleBindingResponses[keyof DeleteRuleBindingResponses];

export type GetRuleBindingData = {
    body?: never;
    path: {
        bindingId: string;
    };
    query?: never;
    url: '/api/rule-bindings/{bindingId}';
};

export type GetRuleBindingErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type GetRuleBindingError = GetRuleBindingErrors[keyof GetRuleBindingErrors];

export type GetRuleBindingResponses = {
    /**
     * OK
     */
    200: RuleBindingDto;
};

export type GetRuleBindingResponse = GetRuleBindingResponses[keyof GetRuleBindingResponses];

export type UpdateRuleBindingData = {
    body: UpdateRuleBindingRequest;
    path: {
        bindingId: string;
    };
    query?: never;
    url: '/api/rule-bindings/{bindingId}';
};

export type UpdateRuleBindingErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type UpdateRuleBindingError = UpdateRuleBindingErrors[keyof UpdateRuleBindingErrors];

export type UpdateRuleBindingResponses = {
    /**
     * OK
     */
    200: RuleBindingDto;
};

export type UpdateRuleBindingResponse = UpdateRuleBindingResponses[keyof UpdateRuleBindingResponses];

export type EvaluateRuleBindingData = {
    body: EvaluateRuleBindingRequest;
    path: {
        bindingId: string;
    };
    query?: never;
    url: '/api/rule-bindings/{bindingId}/evaluate';
};

export type EvaluateRuleBindingErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Unprocessable Content
     */
    422: ProblemDetails;
};

export type EvaluateRuleBindingError = EvaluateRuleBindingErrors[keyof EvaluateRuleBindingErrors];

export type EvaluateRuleBindingResponses = {
    /**
     * OK
     */
    200: RuleEvaluationResult;
};

export type EvaluateRuleBindingResponse = EvaluateRuleBindingResponses[keyof EvaluateRuleBindingResponses];

export type ListSolutionVersionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/solutions/versions';
};

export type ListSolutionVersionsErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type ListSolutionVersionsError = ListSolutionVersionsErrors[keyof ListSolutionVersionsErrors];

export type ListSolutionVersionsResponses = {
    /**
     * OK
     */
    200: Array<SolutionVersionSummaryDto>;
};

export type ListSolutionVersionsResponse = ListSolutionVersionsResponses[keyof ListSolutionVersionsResponses];

export type PublishSolutionVersionData = {
    body: string;
    path?: never;
    query?: never;
    url: '/api/solutions/versions';
};

export type PublishSolutionVersionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Content Too Large
     */
    413: ProblemDetails;
    /**
     * Unsupported Media Type
     */
    415: ProblemDetails;
    /**
     * Unprocessable Content
     */
    422: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type PublishSolutionVersionError = PublishSolutionVersionErrors[keyof PublishSolutionVersionErrors];

export type PublishSolutionVersionResponses = {
    /**
     * OK
     */
    200: PublishSolutionResponse;
    /**
     * Created
     */
    201: PublishSolutionResponse;
};

export type PublishSolutionVersionResponse = PublishSolutionVersionResponses[keyof PublishSolutionVersionResponses];

export type GetSolutionVersionStatusData = {
    body?: never;
    path: {
        solutionVersionId: string;
    };
    query?: never;
    url: '/api/solutions/versions/{solutionVersionId}';
};

export type GetSolutionVersionStatusErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type GetSolutionVersionStatusError = GetSolutionVersionStatusErrors[keyof GetSolutionVersionStatusErrors];

export type GetSolutionVersionStatusResponses = {
    /**
     * OK
     */
    200: SolutionVersionSummaryDto;
};

export type GetSolutionVersionStatusResponse = GetSolutionVersionStatusResponses[keyof GetSolutionVersionStatusResponses];

export type InstallSolutionVersionData = {
    body?: never;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        solutionVersionId: string;
    };
    query?: never;
    url: '/api/solutions/versions/{solutionVersionId}/installations';
};

export type InstallSolutionVersionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type InstallSolutionVersionError = InstallSolutionVersionErrors[keyof InstallSolutionVersionErrors];

export type InstallSolutionVersionResponses = {
    /**
     * OK
     */
    200: InstallSolutionResponse;
    /**
     * Created
     */
    201: InstallSolutionResponse;
};

export type InstallSolutionVersionResponse = InstallSolutionVersionResponses[keyof InstallSolutionVersionResponses];

export type ListSolutionInstallationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/solutions/installations';
};

export type ListSolutionInstallationsErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type ListSolutionInstallationsError = ListSolutionInstallationsErrors[keyof ListSolutionInstallationsErrors];

export type ListSolutionInstallationsResponses = {
    /**
     * OK
     */
    200: Array<SolutionInstallationStatusDto>;
};

export type ListSolutionInstallationsResponse = ListSolutionInstallationsResponses[keyof ListSolutionInstallationsResponses];

export type GetSolutionOperationStatusData = {
    body?: never;
    path: {
        operationId: string;
    };
    query?: never;
    url: '/api/solutions/operations/{operationId}';
};

export type GetSolutionOperationStatusErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type GetSolutionOperationStatusError = GetSolutionOperationStatusErrors[keyof GetSolutionOperationStatusErrors];

export type GetSolutionOperationStatusResponses = {
    /**
     * OK
     */
    200: SolutionOperationStatusDto;
};

export type GetSolutionOperationStatusResponse = GetSolutionOperationStatusResponses[keyof GetSolutionOperationStatusResponses];

export type ResumeSolutionInstallationData = {
    body?: never;
    path: {
        operationId: string;
    };
    query?: never;
    url: '/api/solutions/operations/{operationId}/resume';
};

export type ResumeSolutionInstallationErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type ResumeSolutionInstallationError = ResumeSolutionInstallationErrors[keyof ResumeSolutionInstallationErrors];

export type ResumeSolutionInstallationResponses = {
    /**
     * OK
     */
    200: SolutionOperationStatusDto;
};

export type ResumeSolutionInstallationResponse = ResumeSolutionInstallationResponses[keyof ResumeSolutionInstallationResponses];
